# **Exam**

## Name Of Student: __Atiqa__

## **Section A: Short Answer & Coding Questions**                                                    

### **Modules in Python:**

**a) What is a module in Python? How does it improve code reusability?**

In [ ]:
## Answer Here
module in python is a technique in which we write a code once in .py file and use it accourding to our need in program.
to use module we have import file to access variables, functiona,classes that are pre-defined in the file


**b) Explain the difference between built-in modules and user-defined modules.**

In [ ]:
## Answer Here

built_in modules are predefined module.We use built-in modules directly using import keyword
In Builtin module we donot have to define any function,class or variable before usng it
eg maths module, time module, shutill module

user define modules are defined by user according to our own needs or desire .
before using user define module first we have to define function,classes variables in .py file 
and import the specific file in our program to access the defined function variable in it.

### **NumPy Universal Functions:**

**a) What are universal functions in NumPy? Provide two examples.**

In [ ]:
## Answer Here


# universal function are used to perform element wise operation in arrays
import numpy as np
arr1=np.array([1,2,4])s
arr2=np.array([3,4,6])

print(np.add(arr1,arr2))
print(np.subtract(arr1,arr2))

[ 4  6 10]
[-2 -2 -2]


**b) Write a Python program that creates a NumPy array and applies "np.exp()", "np.sin()", and "np.sqrt()" on it.**

In [9]:
## Answer Here
import numpy as np
arr=np.array([180,90,45])

# new_arr=np.radians(arr)
# print(new_arr)

print("Exponent:     ",np.exp(arr))
print("sin:          ",np.sin(arr))
print("square root: ",np.sqrt(arr))

Exponent:      [1.48938420e+78 1.22040329e+39 3.49342711e+19]
sin:           [-0.80115264  0.89399666  0.85090352]
square root:  [13.41640786  9.48683298  6.70820393]


### **Pandas Operations:**

**a) What is the difference between a Pandas Series and DataFrame?**

In [ ]:
## Answer Here
pandas series is created using sngle column or list 

while pandas dataframe is combination of multiple rows and columns and can be created using multi dimensional arrays,list dictionaries


**b) Write a Python program to create two Pandas Series and concatenate them.**

In [78]:
## Answer Here
import pandas as pd
marks1=[45,56,67]
ser1=pd.Series(marks1)
marks2=[78,45,76]
ser2=pd.Series(marks2)

print(pd.concat([ser1,ser2] ,axis=1))


    0   1
0  45  78
1  56  45
2  67  76


### **File Handling in Python:**

**a) What are the different modes available for opening a file in Python? Explain with examples.**

In [ ]:
## Answer Here
# there are multiplpe modes available for opening file that are:
# "w": it is used to write text in a file 
# if the file is not exist "write" mode automatically create a file and than write the text 

with open("text","w") as f:
    text="Hello there"
    f.write(text)
    # remove the previously existing text and write the new one 

# read mode

with open("text","r") as f:
    text=f.read()
    print(text)
    # read mode is used to read the text in file

# append mode 
with open("text","a") as f:
    text="welcome to python class"
    f.write(text)
    # print(text)

    # this will add the text with the previously existing text 




Hello there


**b) Write a Python program that reads a text file and counts the number of words in it.**

In [ ]:
## Answer Here

with open("text","r") as f:
    text=f.read()
    words=text.split(" ")
    print(len(words))
    

5


### **Random Module:**

**a) What is the use of the random module in Python?**

In [ ]:
## Answer Here
random module is  most commonly used to genegate random numbers with in a given range in array,list 


**b) Write a Python program to generate a 6-digit OTP using the random module.**

In [10]:
## Answer Here
import numpy as np
import random
print(np.random.randint(10, size=6))



[1 1 8 9 2 1]


### **Time and DateTime Module:**

**a) Explain the difference between the time and datetime modules in Python.**

In [21]:
## Answer Here
import time
# time module is specifically used to perform time related operations like cpu execution time , current time

t1=time.time()
for i in range(5000):
    # time.sleep(3)
    i*20
t2=time.time()

print(t2-t1)

from datetime import datetime
# while in datetime module we can perform both time and date related operation
# date=2025-2-
print(datetime.today())


0.00106048583984375
2025-02-17 16:30:10.211492


**b) Write a Python program to print the current date and time in "YYYY-MM-DD HH:MM:SS" format.**

In [22]:
## Answer Here
print(datetime.today())



2025-02-17 16:30:44.803355


### **Exception Handling:**

**a) What is an exception in Python? How does exception handling improve program stability?**

In [ ]:
## Answer Here

exception handlig is useful because it help the program from been chrashed when an error occured

**b) Write a Python program that handles c exceptions using "try-except".**

In [23]:
## Answer Here

try:
    num1=10
    num2=int(input("Enter a number:"))
    x=num1/num2
    print("Division is :",x)

except ZeroDivisionError:
    print("zero denomenator is not valid")



zero denomenator is not valid


### **Object-Oriented Programming (OOP) in Python:**

**a) What is a class in Python? How does it differ from an object?**

In [ ]:
## Answer Here

class s a blue print that is used to create real world objects, it is consist of methods and attributes 
while object are the instance of class that are used to access class attributes and methods 

**b) Write a Python class BankAccount with attributes "account_number", "balance", and methods "deposit()" and "withdraw()".**

 **Create an object and perform transactions.**

In [29]:
## Answer Here

class BankAccount:
    def __init__(self,account_number):
        self.account_number=account_number
        self.balance=10000

    def deposit(self,amount):
        self.balance=self.balance+amount

    def withdrawl(self,amount):
        if self.balance > amount:
           self.balance=self.balance-amount

        else:
            print("Insufficient balance")

    def info(self):
        print(f"current balance is {self.balance}")

a1=BankAccount("2334435")
a1.deposit(2000)
a1.info()
a1.withdrawl(3000)
a1.info()




current balance is 12000
current balance is 9000


### **Inheritance in Python:**

**a) Explain inheritance in Python. What is the purpose of the "super()" function?**

In [ ]:
## Answer Here
inheritance is a python technique in which chld class inherit properties of parent class 
we can access attributes and mrthods of parent class using child class object

super keyword is used to access parent class attribute and methods in child class 


class Vechical:
    def __init__(self,brand):
        self.brand=brand

class Car(Vechical):
    def __init__(self, brand,model):
        super().__init__(brand)
        self.model=model


**b) Write a Python program where "ElectricCar" inherits from "Car" and has an additional attribute "battery_capacity".**

In [ ]:
## Answer Here

class Car:
    def __init__(self,brand):
        self.brand=brand


class ElectricCar(Car):
    def __init__(self, brand,battery_capacity):
        super().__init__(brand)
        self.battery_capacity=battery_capacity


### **Magic Methods in Python:**

**a) What is the purpose of ""__ init __()"" in Python classes?**

In [ ]:
## Answer Here


__init()__ is known as  constructor of class that is automatically called when an object of class is created .
it iis also called dunder method 


**b) Write a class Student with attributes "name" and "marks". Define a method "display()" to show student details.**

 **Create an object of this class.**

In [ ]:
## Answer Here

class Student:
    def __init__(self, name,marks):
        self.name=name
        self.marks=marks


    def display(self):
        print(f"Name: {self.name} Marks:{self.marks}")

### **NumPy Arrays vs. Python Lists:**

**a) Why is a NumPy "array" more efficient than a Python "list" for numerical operations? Also Prove the efficiency.**

In [39]:
## Answer Here

# numpy arrays are efficient because numpy is wrtten in c++ language that faster that python also numpy use contigous memeory location due to which they are faster as compared to lists 
import random



t1=time.time()
list=[]
# print(arr)
for i in range(5000):
    x=i**2
    list.append(x)

t2=time.time()

print(t2-t1)



t1=time.time()
arr=np.arange(5000)
# print(arr)
for i in range(len(arr)):
    arr[i]+5

t2=time.time()

print(t2-t1)



0.01793360710144043
0.0051953792572021484


### **Pandas DataFrame Operations:**

**a) Write a Python program to create a Pandas DataFrame with columns "Name" and "Age". Add a new column "Grade" to it.**

In [44]:
## Answer Here
import pandas as pd
data={
    "Names":["anam","sana","saba"],
    "Age":[12,14,16]
}
df=pd.DataFrame(data)
print(df)
df["Grade"]=["A","B","A"]
print(df)

  Names  Age
0  anam   12
1  sana   14
2  saba   16
  Names  Age Grade
0  anam   12     A
1  sana   14     B
2  saba   16     A


### **Conditional Checking in Pandas:**

**a) Write a Pandas program to filter a DataFrame where the "Age" column has values "greater than 18".**

In [ ]:
## Answer Here

import pandas as pd
data={ '
    "Names":["anam","sana","saba","Ahmed","Anna"],
    "Age":[12,14,16,30,23]
}
df=pd.DataFrame(data)
filter=df[df["Age"]>18]
print(filter)

   Names  Age
3  Ahmed   30
4   Anna   23


### **Concatenating DataFrames in Pandas:**

**a) Write a Python script to concatenate two Pandas DataFrames.**

In [61]:
## Answer Here

data={
    "Names":["anam","sana","saba","Ahmed","Anna"],
    "Age":[12,14,16,30,23]
}
df1=pd.DataFrame(data)

data2={
    "score":[10,2,5,7,8],
    "Domain":["AI","CS","SE","AI","SE"]
}
df2=pd.DataFrame(data2)



new=pd.concat([df1,df2["score"]],axis=1)
new_df=pd.concat([new,df2["Domain"]],axis=1)
print(new_df)

   Names  Age  score Domain
0   anam   12     10     AI
1   sana   14      2     CS
2   saba   16      5     SE
3  Ahmed   30      7     AI
4   Anna   23      8     SE


### **Custom Exception Handling:**

**a) Write a custom exception class "InvalidAgeError". Raise this exception if a user inputs an "age less than 18".**

In [ ]:
## Answer Here

age=int(input("Enter age greate than 18:  "))
if age< 18:
    raise ValueError("InvaldAgeError")

ValueError: InvaldAgeError

## **Section B: Multiple Choice Questions**

**What is the correct way to import all functions from a module?**

a) import module

b) from module import *

c) import module as m

d) include module


**Answer**: b

**What will np.array([2,3,4]) + np.array([5,6,7]) return?**

a) [10,18,28]

b) [7,9,11]

c) [2,3,4,5,6,7]

d) Error

**Answer**: b

**What will random.rand(1,5) return?**

a) A random integer between 1 and 5

b) A random float between 1 and 5

c) A random float between 0 and 1

d) A random float array of shape (1,5)

**Answer**: c

**Which of the following is NOT an exception in Python?**

a) IndexError

b) TypeError

c) KeyError

d) PrintError

**Answer**: d

**What does time.sleep(2) do in Python?**

a) Pauses execution for 2 minutes

b) Pauses execution for 2 seconds

c) Terminates the program

d) Converts time into seconds

**Answer**:  b

**Which method is used to get the current system time?**

a) time.current()

b) time.today()

c) time.time()

d) time.now()

**Answer**: b

**How do you create an instance of a class named Dog?**

a) dog = Dog()

b) Dog(dog)

c) new Dog()

d) dog = Dog.create()

**Answer**: a

**What will happen if a file does not exist when using open('data.txt', 'r')?**

a) It will create a new file

b) It will raise a FileNotFoundError

c) It will return an empty file

d) It will append data to an existing file

**Answer**: b

**Which of the following is TRUE about Python classes?**


a) A class can contain both variables and methods

b) An object cannot be created from a class

c) Classes do not support inheritance

d) Magic methods like __ init __() are optional but recommended

**Answer**: a

## **Additional Coding Questions**

**Write a Python program to generate a random OTP of 6 digits using the random module.**

In [69]:
## Answer Here
print(np.random.randint(10, size=6))


[8 3 1 0 3 9]


**Write a Pandas script to create a DataFrame with "Name, Marks, and Grade", then filter out students who "scored above 80 marks".**

In [72]:
## Answer Here
data={
    "name":["Ali","Saba","raza"],
    "Marks":[89,79,89],
    "garde":["A","B","A"]
}

df=pd.DataFrame(data)
filter=df['Marks']>80

print(df[filter])

   name  Marks garde
0   Ali     89     A
2  raza     89     A


**Write a class Employee with attributes "name and salary". Implement a method "increase_salary()" that increases "salary by 10%".**

In [73]:
## Answer Here
class Employee:
    def __init__(self,name,salary):
        self.name=name
        self.salary=salary
    def increase_salary(self):
        salary=salary+((salary*10/100))


**Write a Pandas program that reads a CSV file, Check NaN values, also create a pivot table with "sum,mean and min aggfuncs".**

In [19]:
## Answer Here
import pandas as pd
car_data=pd.read_csv("car_price_dataset.csv")
# car_data
print(pd.isna(car_data).head())

table=car_data.pivot_table(index=['Brand'], values=['Price'], aggfunc={'sum', 'mean', 'min'})
table



   Brand  Model   Year  Engine_Size  Fuel_Type  Transmission  Mileage  Doors  \
0  False  False  False        False      False         False    False  False   
1  False  False  False        False      False         False    False  False   
2  False  False  False        False      False         False    False  False   
3  False  False  False        False      False         False    False  False   
4  False  False  False        False      False         False    False  False   

   Owner_Count  Price  
0        False  False  
1        False  False  
2        False  False  
3        False  False  
4        False  False  


Price               
                   mean   min      sum
Brand                                 
Audi        8929.373796  2000  9268690
BMW         8704.068068  2000  8695364
Chevrolet   9015.683948  2000  9042731
Ford        8852.570611  2000  9277494
Honda       8665.596630  2000  8743587
Hyundai     8778.279397  2000  8734388
Kia         8880.086066  2000  8666964
Mercedes    8980.087049  2000  8459242
Toyota      8798.184536  2000  8534239
Volkswagen  8928.377451  2000  9106945

### **Best Of Luck....**