In [1]:
import numpy as np

In [2]:
arr=np.array([2,4,6,7])
print(arr)

[2 4 6 7]


In [3]:
# dimension
arr=np.array(34)
print(np.ndim(arr))
arr=np.array([2,4,6,7])

print(type(arr))

0
<class 'numpy.ndarray'>


In [4]:
# dimension of an array
# ndim is used to fnd dimension of an array
print(arr.ndim)

1


In [ ]:
arr1=np.array([2,3,5])
arr2=np.array([[2,3,5],[9,4,5]])
arr3=np.array([[[2,8,3],[1,0,0]],[[4,3,9],[7,3,5]]])
arr4=np.array([[[[[2,3,5],[2,3,5]],[[2,3,5],[2,3,5]]]]])
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim)

1
2
3
5


In [6]:
print(arr3)
print(arr3.shape)
print(arr3.size)
print(arr3.dtype)
print(arr3.nbytes)

[[[2 8 3]
  [1 0 0]]

 [[4 3 9]
  [7 3 5]]]
(2, 2, 3)
12
int32
48


In [7]:
# slicing
arr=np.array([4 ,3 ,9,7 ,3 ,5])
print(arr[-1])
print(arr[3])

5
7


In [8]:
arr=np.array([[1,2,9,7,3],[4,5,2,1,6]])
print(arr[-1::])
print("--------------")
print(arr[1,::-1])
print("------------")
print(arr[:,::-1])
print("------------")
print(arr[::-1,2::-1])
print("-------------")
print(arr[::-1,::-1])

[[4 5 2 1 6]]
--------------
[6 1 2 5 4]
------------
[[3 7 9 2 1]
 [6 1 2 5 4]]
------------
[[2 5 4]
 [9 2 1]]
-------------
[[6 1 2 5 4]
 [3 7 9 2 1]]


In [9]:
arr=np.array([[[1,2,0,0,3],[4,1,2,1,0]],[[9,2,5,8,2],[4,5,2,1,6]]])
print(arr[::-1,::-1,::-1])

[[[6 1 2 5 4]
  [2 8 5 2 9]]

 [[0 1 2 1 4]
  [3 0 0 2 1]]]


In [10]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(arr[1,2])
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[1,1,4])

8
20


In [11]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr[::-1,::-1])
print("-"*20)
print(arr[:,::-1])
print("-"*20)


[[6 5 4]
 [3 2 1]]
--------------------
[[3 2 1]
 [6 5 4]]
--------------------


In [12]:
arr=np.arange(0,20,2)   #make an array of all even numbers
print(arr)
arr=np.arange(1,20,2)   #make an array of all odd numbers
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]


In [13]:
arr=np.linspace(1,15,5)   #make an array of all odd numbers
print(arr)

[ 1.   4.5  8.  11.5 15. ]


In [14]:
# Bit wise operation on an array
arr1=np.array([1,2,6,4])
arr2=np.array([5,2,4,8])
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 6  4 10 12]
[ 5  4 24 32]
[-4  0  2 -4]
[0.2 1.  1.5 0.5]
[1 0 2 4]


In [15]:
arr1=np.array([[1,2,16,4],[5,2,14,8]])
arr2=np.array([[5,22,4,48],[9,21,6,4]])
print(arr1+arr2)
print("-"*50)
print(arr1-arr2)
print("-"*50)
print(arr1*arr2)
print("-"*50)
print(arr1/arr2)
print("-"*50)
print(arr1%arr2)

[[ 6 24 20 52]
 [14 23 20 12]]
--------------------------------------------------
[[ -4 -20  12 -44]
 [ -4 -19   8   4]]
--------------------------------------------------
[[  5  44  64 192]
 [ 45  42  84  32]]
--------------------------------------------------
[[0.2        0.09090909 4.         0.08333333]
 [0.55555556 0.0952381  2.33333333 2.        ]]
--------------------------------------------------
[[1 2 0 4]
 [5 2 2 0]]


In [16]:
arr=np.array([1,9,6,4,2,1,5])

even_num=0
odd_num=0

for i in range(len(arr)):
    if arr[i]%2==0:
        even_num+=arr[i]
    else:
        odd_num+=arr[i]


print("Even Sum:",even_num)
print("Odd Sum:",odd_num)

Even Sum: 12
Odd Sum: 16


In [17]:
# retriving data 

arr=np.array([[[1,2,3],[4,1,0]],[[9,5,8],[5,1,6]]])
print(arr[1,1,2])


6


In [18]:
arr=np.array([1,2,3,4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [19]:
arr=np.array([1,2,3,4,5])
new_arr=arr.astype('f')
print(arr)
print(new_arr.dtype)

[1 2 3 4 5]
float32


In [20]:
unicode_array = np.array(['hello', 'world', '😊'], dtype='U3')
print(unicode_array)
unicode_array = np.array(['hello', 'world', '😊'], dtype='U1')
print(unicode_array)

['hel' 'wor' '😊']
['h' 'w' '😊']


In [21]:
# copy and view function 
arr=np.array([1,2,3,4])
new_arr=arr.copy()
new_arr[2]=12
print(new_arr)
print(new_arr.base)
print(arr)

[ 1  2 12  4]
None
[1 2 3 4]


In [22]:
arr=np.array([1,2,3,4])# view take address
new_arr=arr.view()
new_arr[2]=32
print(new_arr.base)
print(new_arr)
print(arr)

[ 1  2 32  4]
[ 1  2 32  4]
[ 1  2 32  4]


In [23]:
arr=np.array([1,3,4,5,6], ndmin=5)
print(arr)
print(arr.shape)

[[[[[1 3 4 5 6]]]]]
(1, 1, 1, 1, 5)


In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,9])
new_arr=arr.reshape(2,4)
print(new_arr)
print("---------------")
new_arr=arr.reshape(2,2,2)
print(new_arr)

[[1 2 3 4]
 [5 6 7 9]]
---------------
[[[1 2]
  [3 4]]

 [[5 6]
  [7 9]]]


In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,9,11,12,13,15])
new_arr=arr.reshape(4,-1)
print(new_arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  9 11]
 [12 13 15]]


In [26]:
arr=np.array([[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]])

In [27]:
print(arr.reshape(-1))

[ 1  2  3  4  5  6  7  9 11 12 13 15]


In [28]:
# iteration 
arr=np.array([[[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]]])
for layer in arr:
    for row in layer:
        for element in row:
            print(element-1)


0
1
2
3
4
5
6
8
10
11
12
14


In [29]:
arr=np.array([[[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]]])

for i in np.nditer(arr):
    print(i*2)

    

2
4
6
8
10
12
14
18
22
24
26
30


In [30]:
arr=np.array([1,3,5,6,8])
for x in np.nditer(arr,flags=["buffered"], op_dtypes="S"):
    print(x)
    print(x.dtype)

print(arr)
print(arr.dtype)

b'1'
|S11
b'3'
|S11
b'5'
|S11
b'6'
|S11
b'8'
|S11
[1 3 5 6 8]
int32


In [31]:
arr=np.array([1,3,5,6,8])
new=arr.astype("S")
for x in np.nditer(new):
    print(x)
    print(x.dtype)

print(arr)
print(arr.dtype)


b'1'
|S11
b'3'
|S11
b'5'
|S11
b'6'
|S11
b'8'
|S11
[1 3 5 6 8]
int32


In [32]:
arr = np.array([1.9, 2.1, 3.1])

newarr = arr.astype('S')

print(newarr)
print(newarr.dtype)
print(arr.dtype)

[b'1.9' b'2.1' b'3.1']
|S32
float64


In [51]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])

for i in np.nditer(arr[:,:,::2]):
    print(i)



1
3
5
6
8
0
11
13
15
16
18
20


In [75]:
arr=np.array([[1,2,3],[16,17,18]])
print(arr[::-1,::-1])


[[[18 17 16]
  [ 3  2  1]]]


In [78]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[::-1,::-1,::-1])

[[[20 19 18 17 16]
  [15 14 13 12 11]]

 [[ 0  9  8  7  6]
  [ 5  4  3  2  1]]]


In [84]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])

for i in np.nditer(arr[:,1:2,::2]):
    print(i)

6
8
0
16
18
20


In [89]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])
new_arr=arr.reshape(-1)
for i in np.nditer(new_arr[::-2]):
    print(i)

2
4
6
8
0
12
14
16
18
20


In [91]:
for indx, value in np.ndenumerate(arr):
    print(f" Index {indx[0],indx[1],indx[2]} Value: {value}")

 Index (0, 0, 0) Value: 1
 Index (0, 0, 1) Value: 2
 Index (0, 0, 2) Value: 3
 Index (0, 0, 3) Value: 4
 Index (0, 0, 4) Value: 5
 Index (0, 1, 0) Value: 6
 Index (0, 1, 1) Value: 7
 Index (0, 1, 2) Value: 8
 Index (0, 1, 3) Value: 9
 Index (0, 1, 4) Value: 0
 Index (1, 0, 0) Value: 11
 Index (1, 0, 1) Value: 12
 Index (1, 0, 2) Value: 13
 Index (1, 0, 3) Value: 14
 Index (1, 0, 4) Value: 15
 Index (1, 1, 0) Value: 16
 Index (1, 1, 1) Value: 17
 Index (1, 1, 2) Value: 18
 Index (1, 1, 3) Value: 19
 Index (1, 1, 4) Value: 20


In [93]:
# joining array 

arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6 7 8]


In [97]:
arr1=np.array([1,2,3,4])
arr2=np.array([5,6,7,8])
print(np.stack([arr1,arr2]))
print("--------------------------")
print(np.hstack([arr1,arr2]))
print("--------------------------")
print(np.vstack([arr1,arr2]))
print("--------------------------")
print(np.dstack([arr1,arr2]))


[[1 2 3 4]
 [5 6 7 8]]
--------------------------
[1 2 3 4 5 6 7 8]
--------------------------
[[1 2 3 4]
 [5 6 7 8]]
--------------------------
[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]


In [103]:
arr=np.array([1,2,3,4,5,6,7,8,9])
print(np.array_split(arr,5))

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([9])]
