**Numpy Arrays**
  - fast efficient
  - coded in C++
  - use contigious memory location
  - efficient for working wth multi dimensional array
  

In [ ]:
import numpy as np

In [1]:
arr = np.array([2,3,5,6])
print(arr)    #---> 1D
print("--------")

arr1 = np.array([[2,3,5,6]])
print(arr1)   #---> 2D
print("--------")

arr1 = np.array([[[2,3,5,6]]])
print(arr1)   #---> 3D
print("--------")

arr1 = np.array([[2,3,5,6],[0,9,7,6]])
print(arr1)   #---> 2D matrix

# [] are mainly used to show the dimension of array

NameError: name 'np' is not defined

Numpy Array elements can be accessed via index
eg:
arr1=

[[2 3 5 6]

 [0 9 7 6]]

In [ ]:
print(arr1[1,2])
print("-----------")
print(arr1[:])
print("-----------")
print(arr1[0,2])
print("-----------")
print(arr1[1,0])
print("-----------")
print(arr1[0,0])

7
-----------
[[2 3 5 6]
 [0 9 7 6]]
-----------
5
-----------
0
-----------
2


**Multi Dimensional Array**
  - .ndim is used to find the dimension of an array
  - ndim is also used to assign numbers of dimension

In [ ]:
arr2 = np.array([[[1,2,3],[4,5,6]],[[9,0,7],[5,8,3]]])
print(arr2)

arr3 = np.array([2,5,7], ndmin=6)
print(arr3)

[[[1 2 3]
  [4 5 6]]

 [[9 0 7]
  [5 8 3]]]
[[[[[[2 5 7]]]]]]


In [ ]:
print(arr.ndim)
print(arr1.ndim)
print(arr2.ndim)

1
2
3


In [ ]:
print(arr2.shape)  #  2 layer, 2 rows, 3 columns
print(arr2.size)   # total number of elements in array
print(arr2.dtype)   # datatype of each elemnt in array
print(type(arr2))  # datatype of whole array

(2, 2, 3)
12
int32
<class 'numpy.ndarray'>


**Operation on array elemnts**

In [ ]:
arr = np.array([1,3,5,7])

print(arr-1)  # minus 1 from each element of an array
print(arr+10)  # add 10 to each element of an array
print(arr*5)  # add 5 to each element of an array
print(arr/3)  # divide each element of an array b 3
print(arr%3)  # minus 1 from each element of an array

[0 2 4 6]
[11 13 15 17]
[ 5 15 25 35]
[0.33333333 1.         1.66666667 2.33333333]
[1 0 2 1]


In [ ]:
arr1= np.array([1,2,3])
arr2= np.array([4,5,6])

print(arr1*arr2)    # multiply each element with the corresponding element in next array
print(np.dot(arr1,arr2))    # multiply all elements of an array
print(arr1+arr2)    # add each element with the corresponding element in next array
print(arr2-arr1)    # sub each element with the corresponding element in next array

[ 4 10 18]
32
[5 7 9]
[3 3 3]


**Slicing/ extracting multimple elemnts**

In [ ]:
arr = np.array([[[2,4,5],[7,5,5]],[[3,3,2],[9,8,7]]])

print(arr[1,0,2])  # 1st layer, 0th row , 2nd column
print(arr[:,0,2])
print(arr[1,:,2])
print(arr[1,0,:])

2
[5 2]
[2 7]
[3 3 2]


In [ ]:

print("------------")
arr= np.array([1,3,5,7,8,4,8,9])
print(arr[:])
print(arr[:-1])
print(arr[-1])
print(arr[1:5:2])   #from index 1 to 5 , step size =2  arr(start, stop, step_size)



------------
[1 3 5 7 8 4 8 9]
[1 3 5 7 8 4 8]
9
[3 7]


In [ ]:
arr= np.array([[2,3,5,7,4],[3,4,0,0,9]])

print(arr[0,3:])  # 0th layer 3 to last column

[7 4]


**Reversing Array**
   - -1 index is used to reverse an array

In [ ]:
arr = np.array([[[2,4,0],[7,5,5]],[[3,3,2],[9,8,7]]])

print(arr[-1,-1])
print("-----------------")
print(arr[:,::-1]) # reverse rows of sub arrays 
print("------------------")
print(arr[::-1,::-1]) # reverse layers, rows of an array
print("------------------")

arr= np.array([[[2,3,5,7,4],[3,4,0,0,9]],[[3,3,0,1,2],[9,8,7,4,0]]])
print(arr[::-1,::-1,::-1])  # reverse layers, rows and columns of an array


[9 8 7]
-----------------
[[[7 5 5]
  [2 4 0]]

 [[9 8 7]
  [3 3 2]]]
------------------
[[[9 8 7]
  [3 3 2]]

 [[7 5 5]
  [2 4 0]]]
------------------
[[[0 4 7 8 9]
  [2 1 0 3 3]]

 [[9 0 0 4 3]
  [4 7 5 3 2]]]


**Mathematical Operations**

In [ ]:
arr = np.array([2,5,6,0,7,8])
# Element wise operations
print(arr+5)
print(arr-5)
print(arr*5)
print(arr/5)
print(arr%5)

[ 7 10 11  5 12 13]
[-3  0  1 -5  2  3]
[10 25 30  0 35 40]
[0.4 1.  1.2 0.  1.4 1.6]
[2 0 1 0 2 3]


In [ ]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

# Operations performed in the correspondiing elements of both arrays
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

print(min(arr1))
print(max(arr1))

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]
1
4


In [ ]:
A = np.array([2,4,6,8])
B = np.array([1,3,5,7])

print(A*B)   # multiplication is done in the corresponiding elements of both array

print("----Dot Product-------")
A = np.array([2,4,6,8])
B = np.array([1,3,5,7])

print(np.dot(A,B))

[ 2 12 30 56]
----Dot Product-------
100


In [ ]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

result = np.dot(A, B)  # Matrix multiplication
print(result)

[[19 22]
 [43 50]]


**typecasting**
- .dtype is used to know the datatype of an array
- astype() is used to chaange the datatype of an array

In [ ]:
arr = np.array([1776,4,3,4], dtype='S')

In [ ]:
print(arr)
print(arr.dtype)

[b'1776' b'4' b'3' b'4']
|S4


In [3]:
import numpy as np
arr = np.array([2.4,5.4,2.1])
print(arr.dtype)

float64


In [4]:
new_arr = arr.astype('i8')
print(new_arr.dtype)

int64


In [5]:
print(new_arr)

[2 5 2]


In [6]:
#  print array of fixed size

arr = np.array(["pakistan", 'afghistan','Romaniaa', 'india', 'iran'], dtype= 'S5')

In [7]:
print(arr)

[b'pakis' b'afghi' b'Roman' b'india' b'iran']


In [8]:
arr= np.array([6,3,2,1,5,0])
print(arr.astype(bool))

[ True  True  True  True  True False]


In [9]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [10]:
arr= np.array([8,6,7,9,2,4,3,9])
even_arr=0
odd_arr=0
for i in range(len(arr)):
    if arr[i] % 2 == 0:
        even_arr +=arr[i]
    else:
        odd_arr+=arr[i]
print(even_arr)
print(odd_arr)

20
28


**Copy and View Function**
  - Changes using copy function will not be reflected in the original array
  - changes using view function will be reflectrd in original array

In [1]:
import numpy as np
arr = np.array([2, 3, 4, 6, 9, 0, 5])

new_arr = arr.copy()  # Independent copy

new_arr[2] = 80  # Changing copied array

print("Copied Array:", new_arr)  # [2, 3, 80, 6, 9, 0, 5]
print("Original Array:", arr)  # [2, 3, 4, 6, 9, 0, 5] (No change)


type(arr)

Copied Array: [ 2  3 80  6  9  0  5]
Original Array: [2 3 4 6 9 0 5]


numpy.ndarray

In [2]:
arr = np.array([7,5,2,8,0])
new_arr=arr.view()

new_arr[4]=99

print(arr)
print(new_arr)

[ 7  5  2  8 99]
[ 7  5  2  8 99]


In [3]:
new_arr[1]=300

print(arr)
print(new_arr)

[  7 300   2   8  99]
[  7 300   2   8  99]


In [ ]:
arr = np.array([7,5,2,8,0])
arr_copy=arr.copy()

arr_copy[0]=67

arr_view=arr.view()
arr_view[3]=5
print(arr_copy.base)   # this will not belong to any base
print(arr_view.base)
print(arr_copy)
print(arr_view)

None
[7 5 2 5 0]
[67  5  2  8  0]
[7 5 2 5 0]


In [3]:
arr= np.array([9,0,7,9,8,5])
arr_view=arr.view()

arr_view=5
print(arr_view)

5


**Reshapening Array**
   - .reshape(layes, rows, columns)
   - .reshape(3, -1) : unknown dimension:==> here -1 will automtically adjust columns with respect to given rows
   - .reshape(-1) this will flatten multidimensional array in to single row

In [13]:
arr= np.array([2,4,6,3,2,0,6,9])
arr.reshape(2,2,2)

array([[[2, 4],
        [6, 3]],

       [[2, 0],
        [6, 9]]])

In [16]:
arr.reshape(1,4,-1)

array([[[2, 4],
        [6, 3],
        [2, 0],
        [6, 9]]])

In [19]:
arr= np.array([32,54,26,37,20,0,16,99,43,11,23,12])
arr.reshape(2,-1)


array([[32, 54, 26, 37, 20,  0],
       [16, 99, 43, 11, 23, 12]])

In [20]:
arr= np.array([[32, 54, 26, 37, 20,  0],
       [16, 99, 43, 11, 23, 12]])
print(arr.reshape(-1))

[32 54 26 37 20  0 16 99 43 11 23 12]


In [24]:
arr= np.array([32 ,54, 2,6, 37, 20,  0, 16, 99, 43, 11, 23, 12])

for element in arr:
    print(element)

32
54
2
6
37
20
0
16
99
43
11
23
12


In [34]:
arr = np.array([[1,2,3],[4,5,6]])

In [38]:
for row in arr:
    for element in row:
        print(element)

1
2
3
4
5
6


In [40]:
arr = np.array([[[1,2,3],[4,5,6]], [[11,12,13],[14,15,16]]])
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [41]:
for layer in arr:
    for row in layer:
        for element in row:
            print(element)

1
2
3
4
5
6
11
12
13
14
15
16


In [42]:
arr = np.array([[[1,2,3],[4,5,6]], [[11,12,13],[14,15,16]]])

for i in  np.nditer(arr):
    print(i*2)


2
4
6
8
10
12
22
24
26
28
30
32


In [51]:
arr = np.array([[[1,9,8],[4,5,6]], [[11,12,13],[14,15,16]]])

for i in  np.nditer(arr):
  
    print(i >5)

False
True
True
False
False
True
True
True
True
True
True
True


In [55]:
# import numpy as np
arr =np.array([[1,3,4,6],[7,4,7,8]])

for index, value in np.ndenumerate(arr):
    print(f"index: {index} Value:{value}")

index: (0, 0) Value:1
index: (0, 1) Value:3
index: (0, 2) Value:4
index: (0, 3) Value:6
index: (1, 0) Value:7
index: (1, 1) Value:4
index: (1, 2) Value:7
index: (1, 3) Value:8


In [61]:
arr1 = np.array([[0,1,2,3],[2,4,8,6]])
arr2 = np.array([[4,5,6,7],[1,3,5,7]])

new_arr= np.concatenate([arr1,arr2])
print(new_arr)

[[0 1 2 3]
 [2 4 8 6]
 [4 5 6 7]
 [1 3 5 7]]


In [ ]:
print(np.stack([arr1, arr2])) # both arrays have diffrent layers
print("*"*30)
print(np.hstack([arr1, arr2]))  # rows concate to horizontal
print("*"*30)
print(np.vstack([arr1, arr2]))   # both arrays are in single row
print("*"*30)
print(np.dstack([arr1, arr2]))   # first row of both arrays change to first column and second column making first layer
                                # second row of both arrays change to first column and second column making second layer
print("*"*30)

[[[0 1 2 3]
  [2 4 8 6]]

 [[4 5 6 7]
  [1 3 5 7]]]
******************************
[[0 1 2 3 4 5 6 7]
 [2 4 8 6 1 3 5 7]]
******************************
[[0 1 2 3]
 [2 4 8 6]
 [4 5 6 7]
 [1 3 5 7]]
******************************
[[[0 4]
  [1 5]
  [2 6]
  [3 7]]

 [[2 1]
  [4 3]
  [8 5]
  [6 7]]]
******************************


**Split**
  - np.array_split(arr,5) this will split the array in to 5 sub arrays keeping the dimensions same

In [68]:
arr = np.array([[[1,9,8],[4,5,6]], [[11,12,13],[14,15,16]]])
print(np.array_split(arr,4))

[array([[[1, 9, 8],
        [4, 5, 6]]]), array([[[11, 12, 13],
        [14, 15, 16]]]), array([], shape=(0, 2, 3), dtype=int32), array([], shape=(0, 2, 3), dtype=int32)]


In [69]:
print(np.array_split(arr,1))

[array([[[ 1,  9,  8],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])]


**Itreating an array row wise and comumn wise**

   - " F " == column iteration
   - " C " == row iteration



In [72]:
arr= np.array([[2,3,4,5,1,6],[0,4,3,7,8,5]])

In [ ]:
for i in np.nditer(arr, order='C'):  # row iteration
    print(i)

2
3
4
5
1
6
0
4
3
7
8
5


In [ ]:
for i in np.nditer(arr, order='F'):   #column iteration
    print(i)

2
0
3
4
4
3
5
7
1
8
6
5


In [78]:
arr= np.array([2,3,4,5])

for i in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
    print(i)
    # print(type(i))

b'2'
b'3'
b'4'
b'5'


In [79]:
for i in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
    print(i)

b'2'
b'3'
b'4'
b'5'


**Searching of an array**
  - where() :this will serach of element in an array and return its index

In [80]:
arr = np.array([34,45,6,7,2,67])

In [83]:
print(np.where(arr==2))

(array([4], dtype=int64),)


In [99]:
import time

list=[3,4,5,6]
arr =np.array([0,8,5,4])
t1=time.time()
for i in range(100000):
    for i in list:
        i*3
t2= time.time()
print(t2-t1)


0.07490181922912598


In [100]:

arr =np.array([0,8,5,4])
t3=time.time()
for i in range(100000):
    for i in arr:
        i*3
t4= time.time()
print(t4-t3)

0.27037525177001953


In [102]:
arr= np.array([[2,3,4,5,1,6],[2,3,4,5,1,6],[0,4,3,7,8,5]])
print(np.where(arr==8))

(array([2], dtype=int64), array([4], dtype=int64))


In [106]:
arr=arr.reshape(-1)
arr

array([2, 3, 4, 5, 1, 6, 2, 3, 4, 5, 1, 6, 0, 4, 3, 7, 8, 5])

**Sorting using numpy sort function**

In [111]:
print(arr:=np.sort(arr))
arr

[0 1 1 2 2 3 3 3 4 4 4 5 5 5 6 6 7 8]


array([0, 1, 1, 2, 2, 3, 3, 3, 4, 4, 4, 5, 5, 5, 6, 6, 7, 8])

In [112]:
arr= np.array([False, True, True, False, True,True, False])

print(np.sort(arr))

[False False False  True  True  True  True]


In [119]:
arr= np.array(["Raza","Sabrina","Fida","Kashif", "Anam","Asim"])
print(np.sort(arr))

['Anam' 'Asim' 'Fida' 'Kashif' 'Raza' 'Sabrina']


**Argsort**

this will sort the second row first and than the first one

In [137]:
arr = np.array([[1, 3], [4, 1], [2, 5],[0,3],[2,3],[0,0]])
sorted_arr = arr[arr[:,1].argsort()]
print(sorted_arr)

[[0 0]
 [4 1]
 [1 3]
 [0 3]
 [2 3]
 [2 5]]


**Creating Filter**
  - single condition 
  - multi condition

In [139]:
arr=np.array([2,5,3,7,4,8,9,6,8,3,2])

mask= arr%2==1
print(arr[mask])


[5 3 7 9 3]


In [142]:
arr=np.array([2,12,43,87,49,89,99,67,23,36,32])

mask= arr>50
print(arr[mask])

[87 89 99 67]


In [146]:
arr = np.array([34,33,67,78,89,0,673])
filter= (arr>50) & (arr<100)

print(arr[filter])

[67 78 89]


In [171]:
arr= np.array(["Raza","Sabrina","Fida","Kashif", "Anam","Asim","Zain","Soanm","Riffat"])
filter = np.char.startswith(arr, "R")
print(arr[filter])

['Raza' 'Riffat']


In [172]:
filter = np.char.endswith(arr, "n")
print(arr[filter])

['Zain']


In [187]:
arr= np.array(["Raza","Sabrina","Fida","Kashif", "Anam","Asim","Zain","Soanm","Riffat"])

filter=np.char.find(arr,"0")
print(arr[filter])

['Riffat' 'Riffat' 'Riffat' 'Riffat' 'Riffat' 'Riffat' 'Riffat' 'Riffat'
 'Riffat']


In [177]:
filter= np.char.str_len(arr)==4
print(arr[filter])


['Raza' 'Fida' 'Anam' 'Asim' 'Zain']


In [166]:
arr = np.array([7,32,2,9,7,0,5])
filter = arr>5
print(filter)
print(arr[filter])

[ True  True False  True  True False False]
[ 7 32  9  7]


**Rand function**

   - .arange(1,10): used to generate random integers of given range
   - np.random.rand(1,10): this will generate an array of 10 length with elements between 0 to 1
   - np.random.randint(20) this will generate any single integer number in range of 20
   - np.random.random_sample(10) will generate random numbers b/w 0 to 1
   - np.random.uniform(10): will generate floating point number in range of 20

In [197]:
arr=np.arange(100)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [198]:
arr= np.random.rand(1,10)
print(arr)

[[0.75476993 0.84266704 0.75685161 0.6839626  0.42738654 0.68794655
  0.22325911 0.71789479 0.29586182 0.46680228]]


In [199]:
arr= np.random.randint(20)
print(arr)

19


In [200]:
arr= np.random.random_sample(10)
print(arr)

[0.44732266 0.54227039 0.465713   0.03276785 0.9578258  0.92343162
 0.66370104 0.45517097 0.17763966 0.78265171]


In [201]:
print("floating: ",np.random.uniform(10))

floating:  8.01445034065732


In [ ]:
arr=np.random.randint(10, size=(10)) # will generate rray of 10 elements b/w 1 to 10
print(arr)

[5 9 3 5 5 3 1 0 4 0]


In [204]:
print(np.random.randint(10,size=(5,5)))

[[8 0 0 7 8]
 [2 8 0 4 2]
 [5 7 0 8 7]
 [5 6 3 6 8]
 [1 8 1 6 8]]


In [205]:
print(np.random.randint(10, size=(2,1,3)))

[[[5 9 5]]

 [[3 9 5]]]


In [207]:
x=np.random.randint(100,size=10)
print(x)

[87  9 56  9 11  0 66 95 44 30]


choice keyword is used to make random choice

In [220]:
from numpy import random
print(arr)
print(random.choice(arr))

[5 9 3 5 5 3 1 0 4 0]
0


In [229]:
import random

arr = np.array([200,399,478,523,679])
x=random.choices(arr, k=3)
print(x)

[399, 523, 399]


In [223]:
import random
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(random.choices(numbers, k=3)) 

[3, 5, 9]


**.uniform()**
   - his will used to generate rndom floating point value


In [237]:
print(random.uniform(1,5))
arr=np.random.uniform(1,10,size=(3))  
print(arr)

3.825670307597841
[7.74307128 3.54942963 9.20366956]


In [238]:
print(np.random.uniform(1, 10, size=5))

[1.32766174 7.87919074 8.44960608 5.63615654 4.23430353]


random.randn() is used to generate random numbers in cluding both positive and negaatve

In [239]:
print(np.random.randn(10))

[ 0.39344902  0.33342573  0.32476573  0.12379862 -1.43349892 -1.48937568
 -0.39358045 -0.65896867  1.178521   -0.9557834 ]


**random.shuffle(): this will randomly shuffle array elements**

In [243]:
arr= np.array(["Raza","Sabrina","Fida","Kashif", "Anam","Asim","Zain","Soanm","Riffat"])

np.random.shuffle(arr)
print(arr)

['Soanm' 'Raza' 'Riffat' 'Sabrina' 'Fida' 'Kashif' 'Anam' 'Asim' 'Zain']


In [246]:
x = np.random.choice([True, False],size=10)
print(x)

[False False False  True  True  True False  True False False]


seed(value ) : seed function will print the same random numbers for the particular value

In [251]:
np.random.seed(2)
rr= np.random.randint(1,10, size=10)
print(arr)

[8 9 1 9 6 2 2 5 6 4]


In [252]:
np.random.seed(2)
rr= np.random.randint(1,10, size=10)
print(arr)

[8 9 1 9 6 2 2 5 6 4]


generate an array of numbers wth specified probablity

In [255]:
arr=np.array([3,6,2,9,8])
x=random.choice(arr, p=(0.2,0.4,0.2,0.1,0.1), size=(5,5))
print(x)

TypeError: Random.choice() got an unexpected keyword argument 'p'

In [256]:
arr = np.array([2.342,-3.45,0.897,-2.411])
print(np.floor(arr))

[ 2. -4.  0. -3.]


In [257]:
arr = np.array([2.342,-3.45,0.897,-2.411])
print(np.ceil(arr))

[ 3. -3.  1. -2.]


In [258]:
arr = np.array([2.342,-3.45,0.897,-2.411])
print(np.around(arr))

[ 2. -3.  1. -2.]


### np.add.reduce is used only with the scalar values means it only accept one argument

   - by default row elements of arr1 added to arr2
   - axis is ued to change the direction of addtion of elements


In [261]:
arr1 = np.array([1,2,4,5])
arr2= np.array([6,7,8,9])

print(np.add.reduce([arr1,arr2]))
print(np.add.reduce([arr1,arr2], axis=1))

[ 7  9 12 14]
[12 30]


### Cummulative Sum

In [266]:
arr1=np.array([1,3,5,6,7,9])
arr2=np.array([2,3,5,6,3,1])

print(np.cumsum([arr1,arr2],axis=1))
print("*"*20)
print(np.cumsum([arr1,arr2]))

[[ 1  4  9 15 22 31]
 [ 2  5 10 16 19 20]]
********************
[ 1  4  9 15 22 31 33 36 41 47 50 51]


### cummulative product
  - multiply to the nex elemnt of array

In [267]:
arr1 = np.array([2,3,4,5])
arr2 = np.array([6,7,8,9])

print(np.cumprod([arr1, arr2], axis=1))

[[   2    6   24  120]
 [   6   42  336 3024]]


In [270]:
print(np.lcm.reduce(arr1))
print(np.lcm(arr1, arr2))
print(np.lcm.reduce(arr1))


60
[ 6 21  8 45]
60


In [272]:
print(np.gcd.reduce(arr1))
print(np.gcd(arr1,arr2))

1
[2 1 4 1]


In [273]:
print(np.pi/2)

1.5707963267948966


In [274]:
np.sin(90)

0.8939966636005579

In [276]:
arr= np.array([30,60,90,180,170,360])
n_arr= np.radians(arr)
print(n_arr)

[0.52359878 1.04719755 1.57079633 3.14159265 2.96705973 6.28318531]


In [277]:
print(np.degrees(n_arr))

[ 30.  60.  90. 180. 170. 360.]


### inverse of trignometry 


In [280]:
arr= np.array([30,60,90,180])
n_arr=np.radians(arr)
print(np.arccos(n_arr))

[1.01972674        nan        nan        nan]


C:\Users\PMLS\AppData\Local\Temp\ipykernel_20548\2285333456.py:3: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(n_arr))


In [281]:
base=10
perp=4

print(np.hypot(base,perp))

10.770329614269007


In [282]:
arr=np.array([np.pi, np.pi/2, np.pi/3, np.pi/4, np.pi/6])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[1.22464680e-16 1.00000000e+00 8.66025404e-01 7.07106781e-01
 5.00000000e-01]
[-1.00000000e+00  6.12323400e-17  5.00000000e-01  7.07106781e-01
  8.66025404e-01]
[-1.22464680e-16  1.63312394e+16  1.73205081e+00  1.00000000e+00
  5.77350269e-01]


## **--> Pandas**
  - pandas is a python librry used for data analysis
  - it help to analyze big data and help to make statistical theories
  - clean data nad make it in a readable format
#### **most probably used:**
  - to find the corelation between multiple columns
  - average, min, max value

In [1]:
import pandas as pd

### **seires**

 - it is a datastructure that is created usng single column of data and generate index automatically
 - by default its index sarts from zero 
 - index can be cusstomize using index parameter inside series function


In [ ]:
data=["Lawer","Student", "Student","Developer","Scientist"]


series=pd.Series(data,index=[1,2,3,4,5])
print(series)

1        Lawer
2      Student
3      Student
4    Developer
5    Scientist
dtype: object


we can also create  pandas series using dictionaries 
   - its key act as index values
   - Values act as data item need to be converted into pndas series
   - we can select specific data to print using keys
   - type() is used to find the datatype


In [17]:
data={1:"nomi",2:"Adam",3:"Kashan",4:F"arzin",5:"Debu"}
ser=pd.Series(data)
print(ser)
type(ser)

1      nomi
2      Adam
3    Kashan
4     arzin
5      Debu
dtype: object


pandas.core.series.Series

In [15]:
print(pd.Series(data, index=[3,5]))

3    Kashan
5      Debu
dtype: object


### **Dataframe:**
 - it is a multi dimensional array of data columns
 - dataframe is much simiilar to tables

In [48]:
data={
    "Names":["Anam","Sara","Ali","Noman","Faran"],
    "Age":[23,34,32,22,24],
    "Salary":[20000,22000,32000,24000,30000]
}

In [49]:
df = pd.DataFrame(data)
print(df)
type(df)

   Names  Age  Salary
0   Anam   23   20000
1   Sara   34   22000
2    Ali   32   32000
3  Noman   22   24000
4  Faran   24   30000


pandas.core.frame.DataFrame

In [51]:
names=df["Names"]
print(names)
type(names)

0     Anam
1     Sara
2      Ali
3    Noman
4    Faran
Name: Names, dtype: object


pandas.core.series.Series

In [ ]:
sub_data=df[["Age","Salary"]]
print(sub_data)

   Age  Salary
0   23   20000
1   34   22000
2   32   32000
3   22   24000
4   24   30000


### **.loc()**
  - loc is used to find the specified row
  - only the details of specified row are printed
  - multiple index wth comma is used to access multiple columns
  - multiple data can be accessed


In [62]:
print(df.loc[0])

print("-"*30)
print(df.loc[0:4])  # specify the number of row to be accessed from 0 to 4
type(df.loc[0:4])

Names      Anam
Age          23
Salary    20000
Name: 0, dtype: object
------------------------------
   Names  Age  Salary
0   Anam   23   20000
1   Sara   34   22000
2    Ali   32   32000
3  Noman   22   24000
4  Faran   24   30000


pandas.core.frame.DataFrame

In [63]:
print(df.loc[[0,2]])  # this will only print the specified columns  0 and 2
                      # multiple brackets are use to print multiple data
# print(df.loc[[0,3]])
# print(df.loc[0,3])

  Names  Age  Salary
0  Anam   23   20000
2   Ali   32   32000


.loc() can also used to accessed named index

In [94]:
indx=['i','ii','iii','iv']
data={
    "Brand":["lenovo","Dell","Hp","Acer"],
    "Price":[20000,23000,40000,41000],
    "Product":["Laptop","PC","Monito","Headset"]
}

df=pd.DataFrame(data, index=indx)
print(df)

      Brand  Price  Product
i    lenovo  20000   Laptop
ii     Dell  23000       PC
iii      Hp  40000   Monito
iv     Acer  41000  Headset


In [96]:
print(df.loc[["ii",'iv']])

   Brand  Price  Product
ii  Dell  23000       PC
iv  Acer  41000  Headset


In [69]:
print(df.loc[['i']])

print("-"*30)
print(df.loc['i'])

    Brand  Price Product
i  lenovo  20000  Laptop
------------------------------
Brand      lenovo
Price       20000
Product    Laptop
Name: i, dtype: object


## **Reading CSV file to Dataframes**

In [4]:
import pandas as pd
df = pd.read_csv('dataset\car_price_dataset.csv')
df

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
0            Kia       Rio  2020          4.2    Diesel          Manual   
1      Chevrolet    Malibu  2012          2.0    Hybrid       Automatic   
2       Mercedes       GLA  2020          4.2    Diesel       Automatic   
3           Audi        Q5  2023          2.0  Electric          Manual   
4     Volkswagen      Golf  2003          2.6    Hybrid  Semi-Automatic   
...          ...       ...   ...          ...       ...             ...   
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic   
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic   
9997         BMW  3 Series  2010          3.0    Petrol       Automatic   
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic   
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual   

      Mileage  Doors  Owner_Count  Price  
0      289944      3            5   8501  
1        5356      2            3  12092  
2      231440      4            2  11171  
3      160971      2            1  11780  
4      286618      3            3   2867  
...       ...    ...          ...    ...  
9995     5794      2            4   8884  
9996   168000      2            1   6240  
9997    86664      5            1   9866  
9998   225772      4            1   4084  
9999   157882      3            3   3342  

[10000 rows x 10 columns]

In [5]:
print(df.head().to_string())

        Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  Doors  Owner_Count  Price
0         Kia     Rio  2020          4.2    Diesel          Manual   289944      3            5   8501
1   Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356      2            3  12092
2    Mercedes     GLA  2020          4.2    Diesel       Automatic   231440      4            2  11171
3        Audi      Q5  2023          2.0  Electric          Manual   160971      2            1  11780
4  Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618      3            3   2867


In [6]:
print(df.head(5).to_string())

print("-"*100)
print(df.tail(5).to_string())

        Brand   Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  Doors  Owner_Count  Price
0         Kia     Rio  2020          4.2    Diesel          Manual   289944      3            5   8501
1   Chevrolet  Malibu  2012          2.0    Hybrid       Automatic     5356      2            3  12092
2    Mercedes     GLA  2020          4.2    Diesel       Automatic   231440      4            2  11171
3        Audi      Q5  2023          2.0  Electric          Manual   160971      2            1  11780
4  Volkswagen    Golf  2003          2.6    Hybrid  Semi-Automatic   286618      3            3   2867
----------------------------------------------------------------------------------------------------
           Brand     Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  Doors  Owner_Count  Price
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic     5794      2            4   8884
9996   Chevrolet    Impala  2002          1.4  Electric       Aut

### **shape:**
   - to know about number of rows and columns

In [7]:
df.shape

(10000, 10)

In [8]:
df_models=df["Model"]
print(df_models)
type(df_models)

0            Rio
1         Malibu
2            GLA
3             Q5
4           Golf
          ...   
9995      Optima
9996      Impala
9997    3 Series
9998    Explorer
9999      Tiguan
Name: Model, Length: 10000, dtype: object


pandas.core.series.Series

In [9]:
df_brand_yr= df[['Brand','Year']]
print(df_brand_yr)
type(df_brand_yr)

           Brand  Year
0            Kia  2020
1      Chevrolet  2012
2       Mercedes  2020
3           Audi  2023
4     Volkswagen  2003
...          ...   ...
9995         Kia  2004
9996   Chevrolet  2002
9997         BMW  2010
9998        Ford  2002
9999  Volkswagen  2001

[10000 rows x 2 columns]


pandas.core.frame.DataFrame

#### **accessing specified rows and columns from the dataset**

In [10]:
sub_set = df.loc[0:10,["Brand","Price","Engine_Size"]]
# subset = df.loc[0:2, ['Brand', 'Model','Doors']]

print(sub_set)

         Brand  Price  Engine_Size
0          Kia   8501          4.2
1    Chevrolet  12092          2.0
2     Mercedes  11171          4.2
3         Audi  11780          2.0
4   Volkswagen   2867          2.6
5       Toyota   7242          2.7
6        Honda  11208          3.4
7          Kia   7950          4.7
8          Kia   9926          2.6
9       Toyota   6545          3.1
10         BMW   5863          1.3


### **Accessing rows based on conditions**
  - each condition is wraped in round brackets

In [11]:
filter_row = df['Year']==2018
print(df[filter_row].head().to_string())

         Brand     Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  Doors  Owner_Count  Price
20   Chevrolet   Equinox  2018          1.8    Hybrid       Automatic    21261      2            1  13374
69     Hyundai    Tucson  2018          2.8    Petrol          Manual   160349      4            3   9093
78     Hyundai    Sonata  2018          2.0    Hybrid       Automatic   121567      4            4  11568
111        BMW  3 Series  2018          2.3  Electric  Semi-Automatic    99243      3            3  11815
113      Honda      CR-V  2018          3.0    Hybrid  Semi-Automatic   180938      4            3   9881


In [12]:
filter2=df[(df['Year']==2020) | ((df["Model"]=="Impala") & (df["Fuel_Type"]=="Electric"))]
print(filter2.head().to_string())

         Brand     Model  Year  Engine_Size Fuel_Type    Transmission  Mileage  Doors  Owner_Count  Price
0          Kia       Rio  2020          4.2    Diesel          Manual   289944      3            5   8501
2     Mercedes       GLA  2020          4.2    Diesel       Automatic   231440      4            2  11171
28         BMW  3 Series  2020          4.7  Electric  Semi-Automatic   210767      3            3  12584
54         Kia    Optima  2020          3.2  Electric          Manual    88070      3            5  13538
81  Volkswagen    Tiguan  2020          1.7    Petrol       Automatic   195565      2            5   9388


### **Accessing specifc cell with ( iat / at )**

- **iat: it take the integer values means row number or column number and print the value at specific match**
- **at : it take the row number and column name and print the value at that specific match**

In [14]:
model_index_2= df.at[1,"Brand"]
print(model_index_2)

Chevrolet


In [32]:
# print(df.head(5).to_string())
print()
print(df.at[4,"Transmission"])


Semi-Automatic


In [31]:
print(df.iat[4,2])
print(df.iat[4,5])
print(df.iat[4,4])

2003
Semi-Automatic
Hybrid


### **pop function in pandas**

  - **pop function will return the column that is droped and drop the column permanently from original dataframe**

In [42]:
df = pd.DataFrame([['1993', 'Avi', 5, 41, 70, 'Bob'],  
                   ['1994', 'Cathy', 10, 1, 22, 'Cathy'],  
                   ['1995', 'Cathy', 24, 11, 44, 'Bob'],  
                   ['1996', 'Bob', 2, 11, 10, 'Avi'],  
                   ['1998', 'Avi', 20, 10, 40, 'Avi'], 
                   ['1999', 'Avi', 50, 8, 11, 'Cathy']], 
                  columns=('Patients', 'Name', 'Avi', 'Bob', 'Cathy', 'Aname'))

df 


Patients   Name  Avi  Bob  Cathy  Aname
0     1993    Avi    5   41     70    Bob
1     1994  Cathy   10    1     22  Cathy
2     1995  Cathy   24   11     44    Bob
3     1996    Bob    2   11     10    Avi
4     1998    Avi   20   10     40    Avi
5     1999    Avi   50    8     11  Cathy

In [43]:
poped_col=df.pop("Cathy")
print(poped_col)

0    70
1    22
2    44
3    10
4    40
5    11
Name: Cathy, dtype: int64


In [44]:
pop_col2=df.pop("Aname")
print(pop_col2)
print(df)

0      Bob
1    Cathy
2      Bob
3      Avi
4      Avi
5    Cathy
Name: Aname, dtype: object
  Patients   Name  Avi  Bob
0     1993    Avi    5   41
1     1994  Cathy   10    1
2     1995  Cathy   24   11
3     1996    Bob    2   11
4     1998    Avi   20   10
5     1999    Avi   50    8


### **Drop function in pandas**
   - **this is also used to remove a specific column but the changes will not be reflected in original dataframe untill we use inplace = True with it**
   - **drop function wll no return any dropped column instead it return the remaining dataframe keeping the remaning dataframe unchanged**
   - **also used to drop rows using index / axis = 0 while axis = 1 is for column**

In [50]:
droped_col=df.drop(["Patients"],axis=1)
print(droped_col)
print(df)

    Name  Avi  Bob
0    Avi    5   41
1  Cathy   10    1
2  Cathy   24   11
3    Bob    2   11
4    Avi   20   10
5    Avi   50    8
  Patients   Name  Avi  Bob
0     1993    Avi    5   41
1     1994  Cathy   10    1
2     1995  Cathy   24   11
3     1996    Bob    2   11
4     1998    Avi   20   10
5     1999    Avi   50    8


In [ ]:
droped_col=df.drop(["Patients"],axis=1,inplace=True)
print(droped_col)  #return none as the original dataframe changed and no copy is created
print(df)

None
    Name  Avi  Bob
0    Avi    5   41
1  Cathy   10    1
2  Cathy   24   11
3    Bob    2   11
4    Avi   20   10
5    Avi   50    8


In [53]:
print(df.drop([5]))

    Name  Avi  Bob
0    Avi    5   41
1  Cathy   10    1
2  Cathy   24   11
3    Bob    2   11
4    Avi   20   10


 ### **Get():**
   - it is a method that is used to get a specified column from a dataframe

In [58]:
print(df.get(["Name","Avi", "Bob"]))

    Name  Avi  Bob
0    Avi    5   41
1  Cathy   10    1
2  Cathy   24   11
3    Bob    2   11
4    Avi   20   10
5    Avi   50    8


In [60]:
df = pd.read_csv("dataset\car_price_dataset.csv")
df

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
0            Kia       Rio  2020          4.2    Diesel          Manual   
1      Chevrolet    Malibu  2012          2.0    Hybrid       Automatic   
2       Mercedes       GLA  2020          4.2    Diesel       Automatic   
3           Audi        Q5  2023          2.0  Electric          Manual   
4     Volkswagen      Golf  2003          2.6    Hybrid  Semi-Automatic   
...          ...       ...   ...          ...       ...             ...   
9995         Kia    Optima  2004          3.7    Diesel  Semi-Automatic   
9996   Chevrolet    Impala  2002          1.4  Electric       Automatic   
9997         BMW  3 Series  2010          3.0    Petrol       Automatic   
9998        Ford  Explorer  2002          1.4    Hybrid       Automatic   
9999  Volkswagen    Tiguan  2001          2.1    Diesel          Manual   

      Mileage  Doors  Owner_Count  Price  
0      289944      3            5   8501  
1        5356      2            3  12092  
2      231440      4            2  11171  
3      160971      2            1  11780  
4      286618      3            3   2867  
...       ...    ...          ...    ...  
9995     5794      2            4   8884  
9996   168000      2            1   6240  
9997    86664      5            1   9866  
9998   225772      4            1   4084  
9999   157882      3            3   3342  

[10000 rows x 10 columns]

 ### Accessing multiple columns using get method()

In [61]:
print(df.get(['Model',"Brand","Price"]))

         Model       Brand  Price
0          Rio         Kia   8501
1       Malibu   Chevrolet  12092
2          GLA    Mercedes  11171
3           Q5        Audi  11780
4         Golf  Volkswagen   2867
...        ...         ...    ...
9995    Optima         Kia   8884
9996    Impala   Chevrolet   6240
9997  3 Series         BMW   9866
9998  Explorer        Ford   4084
9999    Tiguan  Volkswagen   3342

[10000 rows x 3 columns]


### **isin() method in python**
   - **used to search in a specific column**
   - **isin() will always take list object**
   - **return a filter in which True for the satisfied condition else False**
   - **this filter is passed to df to print the values that satisfied the condition in isin() method**

In [69]:
new_df = df['Brand'].isin(["Mercedes","Kia","Audi"])
# print(new_df)
df[new_df]

Brand     Model  Year  Engine_Size Fuel_Type    Transmission  \
0          Kia       Rio  2020          4.2    Diesel          Manual   
2     Mercedes       GLA  2020          4.2    Diesel       Automatic   
3         Audi        Q5  2023          2.0  Electric          Manual   
7          Kia  Sportage  2001          4.7  Electric  Semi-Automatic   
8          Kia  Sportage  2014          2.6    Hybrid          Manual   
...        ...       ...   ...          ...       ...             ...   
9985      Audi        A4  2003          1.4    Hybrid       Automatic   
9986      Audi        A4  2005          3.6    Petrol  Semi-Automatic   
9990      Audi        A3  2019          1.8  Electric          Manual   
9991  Mercedes   E-Class  2017          1.1    Diesel       Automatic   
9995       Kia    Optima  2004          3.7    Diesel  Semi-Automatic   

      Mileage  Doors  Owner_Count  Price  
0      289944      3            5   8501  
2      231440      4            2  11171  
3      160971      2            1  11780  
7      157495      2            2   7950  
8       98700      3            4   9926  
...       ...    ...          ...    ...  
9985   173657      4            3   5426  
9986   241546      4            2   4369  
9990    85496      4            3  11890  
9991   179286      5            1   8214  
9995     5794      2            4   8884  

[2956 rows x 10 columns]

### **sort_values() of a column in pandas**

In [3]:
import numpy as np
import pandas as pd

df = pd.DataFrame([['1999', 'Avi', 5, 41, 70, 'Bob'],  
                   [np.nan, 'Cathy', 10, 1, 22, 'Cathy'],  
                   ['1993', 'Cathy', 24, 11, 44, 'Bob'],  
                   ['1996', 'Bob', 2, 11, 10, 'Avi'],  
                   ['1992', 'Avi', 20, 10, np.nan, 'Avi'], 
                   ['1991', 'Avi', 50, 8, 11, 'Cathy']], 
                  columns=('Patients', 'Name', 'Avi', 'Bob', 'Cathy', 'Aname')) 

df

Patients   Name  Avi  Bob  Cathy  Aname
0     1999    Avi    5   41   70.0    Bob
1      NaN  Cathy   10    1   22.0  Cathy
2     1993  Cathy   24   11   44.0    Bob
3     1996    Bob    2   11   10.0    Avi
4     1992    Avi   20   10    NaN    Avi
5     1991    Avi   50    8   11.0  Cathy

In [4]:
# sorted=
print( df.sort_values('Patients'))   # sort values according to patient values

  Patients   Name  Avi  Bob  Cathy  Aname
5     1991    Avi   50    8   11.0  Cathy
4     1992    Avi   20   10    NaN    Avi
2     1993  Cathy   24   11   44.0    Bob
3     1996    Bob    2   11   10.0    Avi
0     1999    Avi    5   41   70.0    Bob
1      NaN  Cathy   10    1   22.0  Cathy


In [5]:
print( df.sort_values('Bob'))  
print()
print( df.sort_values('Cathy'))  

  Patients   Name  Avi  Bob  Cathy  Aname
1      NaN  Cathy   10    1   22.0  Cathy
5     1991    Avi   50    8   11.0  Cathy
4     1992    Avi   20   10    NaN    Avi
2     1993  Cathy   24   11   44.0    Bob
3     1996    Bob    2   11   10.0    Avi
0     1999    Avi    5   41   70.0    Bob

  Patients   Name  Avi  Bob  Cathy  Aname
3     1996    Bob    2   11   10.0    Avi
5     1991    Avi   50    8   11.0  Cathy
1      NaN  Cathy   10    1   22.0  Cathy
2     1993  Cathy   24   11   44.0    Bob
0     1999    Avi    5   41   70.0    Bob
4     1992    Avi   20   10    NaN    Avi


### **Creating Filters**

In [6]:
filter=df["Avi"]==50
print(df[filter])

  Patients Name  Avi  Bob  Cathy  Aname
5     1991  Avi   50    8   11.0  Cathy


In [7]:
filter=df["Aname"]=="Cathy"
print(df[filter])

  Patients   Name  Avi  Bob  Cathy  Aname
1      NaN  Cathy   10    1   22.0  Cathy
5     1991    Avi   50    8   11.0  Cathy


### **df.describe()**
   - this will print the statical information about the numerical data
   - mean(), median, max, min, percentile varition etc

In [8]:
df.describe()

Avi        Bob      Cathy
count   6.000000   6.000000   5.000000
mean   18.500000  13.666667  31.400000
std    17.615334  13.909230  25.549951
min     2.000000   1.000000  10.000000
25%     6.250000   8.500000  11.000000
50%    15.000000  10.500000  22.000000
75%    23.000000  11.000000  44.000000
max    50.000000  41.000000  70.000000

  ### **isnull() / isna() :**
  - it will return true for null values else false

In [9]:
print(df.isna())
print("-"*50)
print(df.isnull())

   Patients   Name    Avi    Bob  Cathy  Aname
0     False  False  False  False  False  False
1      True  False  False  False  False  False
2     False  False  False  False  False  False
3     False  False  False  False  False  False
4     False  False  False  False   True  False
5     False  False  False  False  False  False
--------------------------------------------------
   Patients   Name    Avi    Bob  Cathy  Aname
0     False  False  False  False  False  False
1      True  False  False  False  False  False
2     False  False  False  False  False  False
3     False  False  False  False  False  False
4     False  False  False  False   True  False
5     False  False  False  False  False  False


In [10]:
# isna().sum / isnull.sum() is used to add all null values in each column of dataframe

print(df.isna().sum())

Patients    1
Name        0
Avi         0
Bob         0
Cathy       1
Aname       0
dtype: int64


### **df.columns**
  - this is used to print all column names od the dataframe

In [11]:
df.columns

Index(['Patients', 'Name', 'Avi', 'Bob', 'Cathy', 'Aname'], dtype='object')

In [12]:
data = {'age': [21, 18, 27, 28],
        'name': ['Zain', 'Iftikhar', 'Saheem', 'Zafar'],
        'address': ['GB', 'ISB', 'KR','LHR']}
 
df = pd.DataFrame(data)
df

age      name address
0   21      Zain      GB
1   18  Iftikhar     ISB
2   27    Saheem      KR
3   28     Zafar     LHR

### **Adding new column in pandas dataframe**
  - we can add new column easily to data frame
    - **df["column name"]=[value]**

In [13]:
df["Gender"]="Male"
df

age      name address Gender
0   21      Zain      GB   Male
1   18  Iftikhar     ISB   Male
2   27    Saheem      KR   Male
3   28     Zafar     LHR   Male

### **insert() function to add new column to dataframe**
   - **use insert function we add a new column in any position by specifying ts index**
   - **df.insert(position,"column Name", values)**

In [14]:
ids=[2012,2013,2024,2022]
df.insert(0,"id", ids)
df

id  age      name address Gender
0  2012   21      Zain      GB   Male
1  2013   18  Iftikhar     ISB   Male
2  2024   27    Saheem      KR   Male
3  2022   28     Zafar     LHR   Male

In [15]:
status=["Married","Un Married", "Married","Married"]
df.insert(5, "Martial_Status", status)

In [16]:
data1={
    "Domain":["AI","CS","CS","IT"],
    "Employment":["Emloyed","Un Employed","Un Employed","Un Employed"]
}
df2=pd.DataFrame(data1)

In [17]:
df.insert(5,"Domain", df2['Domain'])
df

id  age      name address Gender Domain Martial_Status
0  2012   21      Zain      GB   Male     AI        Married
1  2013   18  Iftikhar     ISB   Male     CS     Un Married
2  2024   27    Saheem      KR   Male     CS        Married
3  2022   28     Zafar     LHR   Male     IT        Married

In [18]:
df

id  age      name address Gender Domain Martial_Status
0  2012   21      Zain      GB   Male     AI        Married
1  2013   18  Iftikhar     ISB   Male     CS     Un Married
2  2024   27    Saheem      KR   Male     CS        Married
3  2022   28     Zafar     LHR   Male     IT        Married

### **concate() methods**
   - to add multiple dataframes
   - axis=1 columnwise concatenation
   - axis=0 row  wise concatenation

In [19]:
new_columns={
    "height":['4f','4.4f','5f','4.6f'],
    "weight":[34,47,45,50]
}
df2= pd.DataFrame(new_columns)
df1= pd.DataFrame(data)


In [20]:
new_df=pd.concat([df1,df2], axis=1)
print(new_df)

   age      name address height  weight
0   21      Zain      GB     4f      34
1   18  Iftikhar     ISB   4.4f      47
2   27    Saheem      KR     5f      45
3   28     Zafar     LHR   4.6f      50


 ### **Conadition to remove specific = c columns**

In [21]:
if "weight" in df.columns:
    df.drop(columns="Weght", inplace= True)

else:
    df.insert(3, "Birt year",2025-df["age"])

In [22]:
df

id  age      name  Birt year address Gender Domain Martial_Status
0  2012   21      Zain       2004      GB   Male     AI        Married
1  2013   18  Iftikhar       2007     ISB   Male     CS     Un Married
2  2024   27    Saheem       1998      KR   Male     CS        Married
3  2022   28     Zafar       1997     LHR   Male     IT        Married

In [24]:
if "Birt ear" in df.columns:
    df.drop(columns="Birt year", inplace=True)

df.insert(7,"Status_group",["Young" if age < 18 else "Adult" for age in df['age']])
# df.insert(3, 'status', ['Adult' if age > 18 else 'Minor' for age in df['age']])


In [25]:
df

id  age      name  Birt year address Gender Domain Status_group  \
0  2012   21      Zain       2004      GB   Male     AI        Adult   
1  2013   18  Iftikhar       2007     ISB   Male     CS        Adult   
2  2024   27    Saheem       1998      KR   Male     CS        Adult   
3  2022   28     Zafar       1997     LHR   Male     IT        Adult   

  Martial_Status  
0        Married  
1     Un Married  
2        Married  
3        Married

In [ ]:
df.insert(4,"Random_val", np.random.randint(10, size=len(df)))
df.insert(4,"Random_nums", np.random.randint(10))

### **Slicing Pandas Dataframe**
  - iloc:  --> df.iloc[ start, end ] this will silce he rows of dataframe
  - iloc only take integer values 
  - used to slice both rows and columns

In [50]:
player_list = [['Shahid Afridi', 36, 75, 5428000],
               ['A.B.D Villers', 38, 74, 3428000],
               ['V.Kohli', 31, 70, 8428000],
               ['S.Smith', 34, 80, 4428000],
               ['C.Gayle', 40, 100, 4528000],
               ['J.Root', 33, 72, 7028000],
               ['K.Peterson', 42, 85, 2528000]]
df = pd.DataFrame(player_list, columns=['Names', 'Age', 'Score', 'Salary'])

In [37]:
df.iloc[0:4]

Names  Age  Score   Salary
0  Shahid Afridi   36     75  5428000
1  A.B.D Villers   38     74  3428000
2        V.Kohli   31     70  8428000
3        S.Smith   34     80  4428000

In [ ]:
df.iloc[1:3,[1,2]] #slce rows and columns

Age  Score
1   38     74
2   31     70

In [ ]:
print(df.iloc[4,0])  #slicesingle cell

C.Gayle


In [52]:
filter = df[df['Score']>80].iloc[:,[0,2]]
print(filter)

        Names  Score
4     C.Gayle    100
6  K.Peterson     85


In [53]:
filter = df[df['Score']<80].iloc[:,[0,2]]
print(filter)

           Names  Score
0  Shahid Afridi     75
1  A.B.D Villers     74
2        V.Kohli     70
5         J.Root     72


In [57]:
filter=df[df['Names'].str.startswith('S')].iloc[:,[0,3]]
print(filter)

           Names   Salary
0  Shahid Afridi  5428000
3        S.Smith  4428000


### **.loc () in pandas**
  - take index number or column name in [] of dataframe to be sliced

In [67]:
print(df.loc[0:4,["Names","Salary"]])

           Names   Salary
0  Shahid Afridi  5428000
1  A.B.D Villers  3428000
2        V.Kohli  8428000
3        S.Smith  4428000
4        C.Gayle  4528000


In [74]:
print(df.loc[[0,2],['Names','Salary']])

           Names   Salary
0  Shahid Afridi  5428000
2        V.Kohli  8428000


### **set_index() in pandas**
  - this method allow us to set any column of dataframe as index so that we can access an specific row using name of the index
  - this cahnge will not be reflected in the original dataframe

In [80]:
df_names_indx=df.set_index("Names")
df_names_indx

Age  Score   Salary
Names                             
Shahid Afridi   36     75  5428000
A.B.D Villers   38     74  3428000
V.Kohli         31     70  8428000
S.Smith         34     80  4428000
C.Gayle         40    100  4528000
J.Root          33     72  7028000
K.Peterson      42     85  2528000

In [81]:
df_names_indx.loc['Shahid Afridi','Salary']

5428000

## **Filters in Pandas dataframe**

In [99]:
df = pd.DataFrame({'Name': [' RACHEL  ', ' MONICA  ', ' PHOEBE  ',
                                   '  ROSS    ', 'CHANDLER', ' JOEY    '],
                          
                          'Age': [30, 35, 37, 33, 34, 30],
                          
                          'Salary': [100000, 93000, 818000, 120000, 94000, 95000],
                          
                          'JOB': ['DESIGNER', 'CHEF', 'Designer', 'PALENTOLOGY',
                                  'IT', 'ARTIST']})
# print(dataFrame)
display(df)

Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
1    MONICA     35   93000         CHEF
2    PHOEBE     37  818000     Designer
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

### **multiple conditions in .loc()**

In [91]:
display(df.loc[(df["Salary"]>5000) & (df["Age"] < 45) & df['JOB'].str.startswith("IT"), ["Name", "Salary","Age","JOB"]])

Name  Salary  Age JOB
4  CHANDLER   94000   34  IT

In [97]:
display(df.loc[(df["Salary"]>50000) & (df["Age"] < 35) , ["Name", "Salary","Age","JOB"]])

Name  Salary  Age          JOB
0    RACHEL    100000   30     DESIGNER
3    ROSS      120000   33  PALENTOLOGY
4    CHANDLER   94000   34           IT
5    JOEY       95000   30       ARTIST

### **Filter using Numpy in pandas Dataframe**
  - np.where() this will return bollean dataframe
  - to pint filter dataframe we pass bollean values to df.loc[boolean_values]
  - this will work same as pandas dataframe

In [110]:
filter_np=np.where((df["Salary"]>50000) & (df["Age"]< 35))
# print(filter_np) boolean values
display(df.loc[filter_np])


Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

### **Filter using QUERY in pandas**

In [111]:
display(df.query("(Salary> 50000) & (Age< 35)"))

Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [115]:
display(df.query("(Salary> 50000) & (Age< 35) & (JOB.str.startswith('IT').values)"))

Name  Age  Salary JOB
4  CHANDLER   34   94000  IT

#### **Pandas Boolean indexing multiple conditions**

In [116]:
display(df[(df['Salary']>50000) & (df['Age']<35)])

Name  Age  Salary          JOB
0    RACHEL     30  100000     DESIGNER
3    ROSS       33  120000  PALENTOLOGY
4    CHANDLER   34   94000           IT
5    JOEY       30   95000       ARTIST

In [117]:
display(df[(df['Salary']>50000) & (df['Age']<35) & (df['JOB'].str.startswith("IT"))])

Name  Age  Salary JOB
4  CHANDLER   34   94000  IT

### **Pandas Merging, Joining, and Concatenating**

In [22]:
import pandas as pd
import numpy as np

In [23]:
data1 = {'Name': ['Zaid', 'Junaid', 'Saqeeb', 'Azan'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd']}


data2 = {'Name': ['Abdullah', 'Aqsan', 'Dayan', 'Sayam'],
         'Age': [17, 14, 12, 52],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

d1=pd.DataFrame(data1, index=[1,2,3,4,])
d2=pd.DataFrame(data2, index=[11,22,33,44,])

display(d1, d2)

Name  Age    Address Qualification
1    Zaid   27     Nagpur           Msc
2  Junaid   24     Kanpur            MA
3  Saqeeb   22  Allahabad           MCA
4    Azan   32    Kannuaj           Phd

Name  Age    Address Qualification
11  Abdullah   17     Nagpur         Btech
22     Aqsan   14     Kanpur           B.A
33     Dayan   12  Allahabad          Bcom
44     Sayam   52    Kannuaj        B.hons

### **conacat() method**
  - it is a method that is used to add multiple dataframes by rows or columns
  - axis = 1  :this will add both dataframes by columns / show nan for unknown values
  - axis = 0  :this will add both dataframes by rows and the index remain unchanged

In [ ]:
frame= [d1, d2]

display(pd.concat(frame, axis=1))


Name   Age    Address Qualification      Name   Age    Address  \
1     Zaid  27.0     Nagpur           Msc       NaN   NaN        NaN   
2   Junaid  24.0     Kanpur            MA       NaN   NaN        NaN   
3   Saqeeb  22.0  Allahabad           MCA       NaN   NaN        NaN   
4     Azan  32.0    Kannuaj           Phd       NaN   NaN        NaN   
11     NaN   NaN        NaN           NaN  Abdullah  17.0     Nagpur   
22     NaN   NaN        NaN           NaN     Aqsan  14.0     Kanpur   
33     NaN   NaN        NaN           NaN     Dayan  12.0  Allahabad   
44     NaN   NaN        NaN           NaN     Sayam  52.0    Kannuaj   

   Qualification  
1            NaN  
2            NaN  
3            NaN  
4            NaN  
11         Btech  
22           B.A  
33          Bcom  
44        B.hons

In [26]:
display(pd.concat([d1,d2], axis=0))

Name  Age    Address Qualification
1       Zaid   27     Nagpur           Msc
2     Junaid   24     Kanpur            MA
3     Saqeeb   22  Allahabad           MCA
4       Azan   32    Kannuaj           Phd
11  Abdullah   17     Nagpur         Btech
22     Aqsan   14     Kanpur           B.A
33     Dayan   12  Allahabad          Bcom
44     Sayam   52    Kannuaj        B.hons

In [31]:
data1 = {'Name': ['Zafar', 'Moiz', 'Zaman', 'Salman'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]}

data2 = {'Name': ['Zaman', 'Salman', 'Zakir', 'Zain'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]}

df1 = pd.DataFrame(data1, index=[0, 1, 2, 3])

df2 = pd.DataFrame(data2, index=[2, 3, 6, 7])

display(df1, df1)

Name  Age    Address Qualification  Mobile No
0   Zafar   27     Nagpur           Msc         97
1    Moiz   24     Kanpur            MA         91
2   Zaman   22  Allahabad           MCA         58
3  Salman   32    Kannuaj           Phd         76

Name  Age    Address Qualification  Mobile No
0   Zafar   27     Nagpur           Msc         97
1    Moiz   24     Kanpur            MA         91
2   Zaman   22  Allahabad           MCA         58
3  Salman   32    Kannuaj           Phd         76

## **Join with concat() method**

#### **JOIN = INNER**
**df.concat([df1,df2], join= inner)**
  - ths will only printt the values that are common in both dataframes

In [34]:
display(pd.concat([df1, df2], axis=1, join='inner'))

Name  Age    Address Qualification  Mobile No    Name  Age    Address  \
2   Zaman   22  Allahabad           MCA         58   Zaman   22  Allahabad   
3  Salman   32    Kannuaj           Phd         76  Salman   32    Kannuaj   

  Qualification  Salary  
2           MCA    1000  
3           Phd    2000

#### **join = outer**
  - this will show all values will but the common values are dsplayed for 1 time 

In [36]:
display(pd.concat([df1,df2], axis=1, join='outer'))

Name   Age    Address Qualification  Mobile No    Name   Age    Address  \
0   Zafar  27.0     Nagpur           Msc       97.0     NaN   NaN        NaN   
1    Moiz  24.0     Kanpur            MA       91.0     NaN   NaN        NaN   
2   Zaman  22.0  Allahabad           MCA       58.0   Zaman  22.0  Allahabad   
3  Salman  32.0    Kannuaj           Phd       76.0  Salman  32.0    Kannuaj   
6     NaN   NaN        NaN           NaN        NaN   Zakir  12.0  Allahabad   
7     NaN   NaN        NaN           NaN        NaN    Zain  52.0    Kannuaj   

  Qualification  Salary  
0           NaN     NaN  
1           NaN     NaN  
2           MCA  1000.0  
3           Phd  2000.0  
6          Bcom  3000.0  
7        B.hons  4000.0

**ignore_index()**
 - this will ignore the index of both dataframe and generate index automatically in a sequence

In [42]:
print(pd.concat(frame,ignore_index=True))

       Name  Age    Address Qualification
0      Zaid   27     Nagpur           Msc
1    Junaid   24     Kanpur            MA
2    Saqeeb   22  Allahabad           MCA
3      Azan   32    Kannuaj           Phd
4  Abdullah   17     Nagpur         Btech
5     Aqsan   14     Kanpur           B.A
6     Dayan   12  Allahabad          Bcom
7     Sayam   52    Kannuaj        B.hons


##### **Concatenating DataFrame by setting keys :**

In [43]:
print(pd.concat([df1,df2], keys=['first group','second group']))

                  Name  Age    Address Qualification  Mobile No  Salary
first group  0   Zafar   27     Nagpur           Msc       97.0     NaN
             1    Moiz   24     Kanpur            MA       91.0     NaN
             2   Zaman   22  Allahabad           MCA       58.0     NaN
             3  Salman   32    Kannuaj           Phd       76.0     NaN
second group 2   Zaman   22  Allahabad           MCA        NaN  1000.0
             3  Salman   32    Kannuaj           Phd        NaN  2000.0
             6   Zakir   12  Allahabad          Bcom        NaN  3000.0
             7    Zain   52    Kannuaj        B.hons        NaN  4000.0


In [44]:
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Ali', 'Zubair', 'Sahil', 'Suhaib'], 
        'Age':[27, 24, 22, 32],} 

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']} 

data3 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Mobile Number':['00000', '11111', '66666', '999999'], 
        'Status':['Active', 'Offline', 'Dropped', 'Geraduated']} 

df1 = pd.DataFrame(data1)
df2 = pd.DataFrame(data2)
df3 = pd.DataFrame(data3)

### **merge() method**
  - this method will also help to add multiple datatframes
  - merged is done based on one common column in both dataframes
  - that common column is passed to **on** parameter
  - if the on parameter is not passed the merge is automatically done based on the common column

In [57]:
merged = pd.merge(df1,df2)

print(merged)

  key    Name  Age    Address Qualification
0  K0     Ali   27     Nagpur         Btech
1  K1  Zubair   24     Kanpur           B.A
2  K2   Sahil   22  Allahabad          Bcom
3  K3  Suhaib   32    Kannuaj        B.hons


In [59]:
merged = pd.merge(df1,df2, on='key')
print(merged)


  key    Name  Age    Address Qualification
0  K0     Ali   27     Nagpur         Btech
1  K1  Zubair   24     Kanpur           B.A
2  K2   Sahil   22  Allahabad          Bcom
3  K3  Suhaib   32    Kannuaj        B.hons


In [62]:
merged2 = pd.merge(merged, df3)
print(merged2)

  key    Name  Age    Address Qualification Mobile Number      Status
0  K0     Ali   27     Nagpur         Btech         00000      Active
1  K1  Zubair   24     Kanpur           B.A         11111     Offline
2  K2   Sahil   22  Allahabad          Bcom         66666     Dropped
3  K3  Suhaib   32    Kannuaj        B.hons        999999  Geraduated


### **Sorting by single Column** 
  - #### **sort_values()** 
    this method is used to sort values by columns

In [66]:
data = {
    'Name': ['Alice', 'Bob', 'M Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'Score': [85, 90, 95, 80]
    }
df = pd.DataFrame(data)

#### **by="column name"**
 - to sort te values based on one column we use **by** keyword

In [67]:
sorted= df.sort_values(by="Age", ascending=True)
sorted

Name  Age  Score
0      Alice   25     85
1        Bob   30     90
2  M Charlie   35     95
3      David   40     80

In [68]:
sorted= df.sort_values(by="Score", ascending=True)
sorted

Name  Age  Score
3      David   40     80
0      Alice   25     85
1        Bob   30     90
2  M Charlie   35     95

In [71]:
sorted = df.sort_values(by="Name", ascending=False)
print(sorted)

        Name  Age  Score
2  M Charlie   35     95
3      David   40     80
1        Bob   30     90
0      Alice   25     85


### **Sorting by Multiple Column**

In [72]:
sorted = df.sort_values(by=['Age', 'Score'], ascending=True)
sorted

Name  Age  Score
0      Alice   25     85
1        Bob   30     90
2  M Charlie   35     95
3      David   40     80

In [75]:
sorted = df.sort_values(by=['Score', 'Name'], ascending=False)
sorted

Name  Age  Score
2  M Charlie   35     95
1        Bob   30     90
0      Alice   25     85
3      David   40     80

### **Sorting by Missing Values**

In [77]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [28, None, None, 22]
    }

df = pd.DataFrame(data)
df


Name   Age
0    Alice  28.0
1      Bob   NaN
2  Charlie   NaN
3    David  22.0

In [79]:
sorted = df.sort_values(by='Age',na_position='last')
sorted

Name   Age
3    David  22.0
0    Alice  28.0
1      Bob   NaN
2  Charlie   NaN

In [81]:
sorted = df.sort_values(by='Age', na_position='first')
sorted

Name   Age
1      Bob   NaN
2  Charlie   NaN
3    David  22.0
0    Alice  28.0

### **Pivot Table in pandas**

In [82]:
data = {
    'Product': ['Carrots', 'Broccoli', 'Banana', 'Banana', 'Beans', 'Orange', 'Broccoli', 'Banana'],
    'Category': ['Vegetable', 'Vegetable', 'Fruit', 'Fruit','Vegetable', 'Fruit', 'Vegetable', 'Fruit'],
    'Quantity': [8, 5, 3, 4, 5, 9, 11, 8],
    'Amount': [270, 239, 617, 384, 626, 610, 62, 90]
    }

df = pd.DataFrame(data)
df

Product   Category  Quantity  Amount
0   Carrots  Vegetable         8     270
1  Broccoli  Vegetable         5     239
2    Banana      Fruit         3     617
3    Banana      Fruit         4     384
4     Beans  Vegetable         5     626
5    Orange      Fruit         9     610
6  Broccoli  Vegetable        11      62
7    Banana      Fruit         8      90

#### **df.pivot_table( index="column name", values="column name", aggfunc="Function name" )**

In [84]:
pivot = df.pivot_table(index=['Product'], values=['Amount'], aggfunc='sum')
pivot

Amount
Product         
Banana      1091
Beans        626
Broccoli     301
Carrots      270
Orange       610

In [86]:
pivot = df.pivot_table( index=['Category'], values=['Amount'], aggfunc='sum')
pivot

Amount
Category         
Fruit        1701
Vegetable    1197

### **Multiple column names are set as index**

In [94]:
pivot = df.pivot_table( index=['Product', 'Category'], values=['Amount'], aggfunc=['mean','sum','median','max','min'])
pivot

mean    sum median    max    min
                        Amount Amount Amount Amount Amount
Product  Category                                         
Banana   Fruit      363.666667   1091  384.0    617     90
Beans    Vegetable  626.000000    626  626.0    626    626
Broccoli Vegetable  150.500000    301  150.5    239     62
Carrots  Vegetable  270.000000    270  270.0    270    270
Orange   Fruit      610.000000    610  610.0    610    610

### **Series in Depth**

In [100]:
index=[x for x in 'abcdefghijklmnopqrstuvwxyz']
ser = pd.Series(range(1,27), index=index)
type(ser)

pandas.core.series.Series

#### **series.to_frame("Column name")**
  - this method is used to convert series to dataframe

In [110]:
ser = pd.Series(range(1,27), index=index)
ser1 = ser.to_frame("Integer Values")
display(ser1.head())
print(type(ser1))
print(type(ser))


Integer Values
a               1
b               2
c               3
d               4
e               5

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [115]:
ser= np.arange(12,25)
ser_obj=pd.Series(ser+5, index=ser)
ser_obj.to_frame("Series+5")

Series+5
12        17
13        18
14        19
15        20
16        21
17        22
18        23
19        24
20        25
21        26
22        27
23        28
24        29

##### **accessing elements**

In [124]:
print(ser_obj[-2:] )
print(ser_obj[1:5] )
print(ser_obj[:1] )
print(ser_obj[1:25:2] )

23    28
24    29
dtype: int32
13    18
14    19
15    20
16    21
dtype: int32
12    17
dtype: int32
13    18
15    20
17    22
19    24
21    26
23    28
dtype: int32


#### **Accessing Elements using Index Values**

In [126]:
data = np.array(['a', 's', 'd', 'f', 'g', 'h',
                 'o', 'r', 'p', 'e', 'e', 'k', 'l'])
ser = pd.Series(data, index=[10, 11, 12, 13, 14,
                             15, 16, 17, 18, 19, 20, 21, 22])
ser

10    a
11    s
12    d
13    f
14    g
15    h
16    o
17    r
18    p
19    e
20    e
21    k
22    l
dtype: object

In [134]:
print(ser[19])
print(ser[15])
print(ser[13])

e
h
f


#### Accessing Multiple elements 

In [138]:
print(ser[[13,15,17]])
print(ser[[10, 20]])

13    f
15    h
17    r
dtype: object
10    a
20    e
dtype: object


#### **Access Multiple Elements by Providing Label of Index**

In [141]:
ser = pd.Series(np.arange(3, 9), index=['a', 'b', 'c', 'd', 'e', 'f'])

print(ser[['d','b']])
print(ser[['a','c','f']])
print(ser[['e','b']])

d    6
b    4
dtype: int32
a    3
c    5
f    8
dtype: int32
e    7
b    4
dtype: int32


#### checking for equality of each element in both series

In [142]:
ser1 = pd.Series([2,3,4,5,8,9,6])
ser2 = pd.Series([3,3,3,5,7,8,6])

result= ser1==ser2
print(result)

0    False
1     True
2    False
3     True
4    False
5    False
6     True
dtype: bool


In [148]:
ser1 = pd.Series(np.random.randint(10, size=10))
ser2 = pd.Series(np.random.randint(10, size=10))
print(ser1)
print(ser2)

0    4
1    3
2    1
3    5
4    4
5    6
6    3
7    8
8    0
9    5
dtype: int32
0    2
1    2
2    0
3    4
4    5
5    0
6    4
7    4
8    1
9    1
dtype: int32


In [149]:
result= ser1-ser2
print(result)

0    2
1    1
2    1
3    1
4   -1
5    6
6   -1
7    4
8   -1
9    4
dtype: int32


#### **Mathematical operations on pandas Dataframe**

In [167]:
from numpy import random
# seed(10)
df1= pd.DataFrame({
    "a":[2,4,6,7],
    "b":[9,2,4,5]
})
print(df1)
print("-------------")

df2= pd.DataFrame({
    "a":[5,6,3,2],
    "b":[9,2,5,2]
})
print(df2)


   a  b
0  2  9
1  4  2
2  6  4
3  7  5
-------------
   a  b
0  5  9
1  6  2
2  3  5
3  2  2


#### **Subtraction**
  - to subtract 2 dataframes both must have same column name

In [169]:
print(df1-df2)
print("-"*20)
print(df1+df2)
print("-"*20)
print(df1*df2)
print("-"*20)
print(df1/df2)

   a  b
0 -3  0
1 -2  0
2  3 -1
3  5  3
--------------------
    a   b
0   7  18
1  10   4
2   9   9
3   9   7
--------------------
    a   b
0  10  81
1  24   4
2  18  20
3  14  10
--------------------
          a    b
0  0.400000  1.0
1  0.666667  1.0
2  2.000000  0.8
3  3.500000  2.5


#### **Comparision of dataframes**

In [173]:
res = df1>df2
print(res)
print("-"*20)

res = df1<df2
print(res)
print("-"*20)

res = df1==df2
print(res)

       a      b
0  False  False
1  False  False
2   True  False
3   True   True
--------------------
       a      b
0   True  False
1   True  False
2  False   True
3  False  False
--------------------
       a      b
0  False   True
1  False   True
2  False  False
3  False  False


In [183]:
df1 = pd.DataFrame({'A': [1, 2, None], 'B': [4, None, 6]})
df2 = pd.DataFrame({'A': [1, None, 3], 'B': [None, 5, 6]})

res = df1+df2
print(res)

     A     B
0  2.0   NaN
1  NaN   NaN
2  NaN  12.0


#### **Logical operations on series**

In [182]:
ser1 =pd.Series([False,True, True,False ])
ser2 =pd.Series([True,True,True,False])
print(ser1)
print(ser2)

0    False
1     True
2     True
3    False
dtype: bool
0     True
1     True
2     True
3    False
dtype: bool


In [181]:
res= ser1 | ser2
print(res)
print("-"*20)

res= ser1 & ser2
print(res)

0     True
1     True
2     True
3    False
dtype: bool
--------------------
0    False
1     True
2     True
3    False
dtype: bool


#### **ser.index=[index values]**
used to create index values

In [184]:
ser= pd.Series(["GB",'KR','ISLB','LHR','MLTN','QUT'])
ser

0      GB
1      KR
2    ISLB
3     LHR
4    MLTN
5     QUT
dtype: object

In [187]:
ser.index=['city-1','city-2','city-3','city-4','city-5','city-6']
ser

city-1      GB
city-2      KR
city-3    ISLB
city-4     LHR
city-5    MLTN
city-6     QUT
dtype: object

In [189]:
Date = ['1/1/2018', '2/1/2018', '3/1/2018', '4/1/2018']
Index_name = ['Day 1', 'Day 2', 'Day 3', 'Day 4']

ser= pd.Series(Date, index=Index_name)
ser

Day 1    1/1/2018
Day 2    2/1/2018
Day 3    3/1/2018
Day 4    4/1/2018
dtype: object

In [195]:
Index_name1 = ['Day 10', 'Day 20', 'Day 30', 'Day 40']
ser.index=Index_name
print(ser.index)

Index(['Day 1', 'Day 2', 'Day 3', 'Day 4'], dtype='object')


### **Load data from csv file**

In [199]:
data = """totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4"""

with open("files/f1.csv",'w') as f:
    f.write(data)

print(data)

totalbill_tip, sex:smoker, day_time, size
16.99, 1.01:Female|No, Sun, Dinner, 2
10.34, 1.66, Male, No|Sun:Dinner, 3
21.01:3.5_Male, No:Sun, Dinner, 3
23.68, 3.31, Male|No, Sun_Dinner, 2
24.59:3.61, Female_No, Sun, Dinner, 4
25.29, 4.71|Male, No:Sun, Dinner, 4


In [201]:
df=pd.read_csv("files/f1.csv")
df

totalbill_tip  sex:smoker        day_time   size
16.99            1.01:Female|No         Sun          Dinner    2.0
10.34                      1.66        Male   No|Sun:Dinner    3.0
21.01:3.5_Male           No:Sun      Dinner               3    NaN
23.68                      3.31     Male|No      Sun_Dinner    2.0
24.59:3.61            Female_No         Sun          Dinner    4.0
25.29                 4.71|Male      No:Sun          Dinner    4.0

#### **load csv file with different delimenators**


In [206]:
df = pd.read_csv('files/f1.csv', sep='[, :|_]', engine='python')
df

totalbill   tip Unnamed: 2   sex smoker Unnamed: 5     day    time  \
16.99        NaN  1.01     Female    No    NaN        Sun     NaN  Dinner   
10.34        NaN  1.66        NaN  Male    NaN         No     Sun  Dinner   
21.01       3.50  Male        NaN    No    Sun        NaN  Dinner     NaN   
23.68        NaN  3.31        NaN  Male     No        NaN     Sun  Dinner   
24.59       3.61   NaN     Female    No    NaN        Sun     NaN  Dinner   
25.29        NaN  4.71       Male   NaN     No        Sun     NaN  Dinner   

       Unnamed: 8  size  
16.99         NaN   2.0  
10.34         NaN   3.0  
21.01         3.0   NaN  
23.68         NaN   2.0  
24.59         NaN   4.0  
25.29         NaN   4.0

#### **Saving Pandas to CSV File**

In [207]:
name= ["asam", "zain", "sameen", "dayan"]
deg = ["MBA", "BCA", "M.Tech", "MBA"]
scr = [90, 40, 80, 98]

df= pd.DataFrame({"Name":name, "Degree":deg, "Score":scr})
df

Name  Degree  Score
0    asam     MBA     90
1    zain     BCA     40
2  sameen  M.Tech     80
3   dayan     MBA     98

index= False : parameter is used to remove the auto generted index from csv file

In [219]:
df.to_csv('files/f2.csv', index=False)

In [220]:
df1=pd.read_csv('files/f2.csv')
df1

Name  Degree  Score
0    asam     MBA     90
1    zain     BCA     40
2  sameen  M.Tech     80
3   dayan     MBA     98

### **Using Different seperators**

In [221]:
data = {
    'Name': ['Amit', 'Cody', 'Drew'],
    'Age': [20,21,25]
    }
df= pd.DataFrame(data)
df

Name  Age
0  Amit   20
1  Cody   21
2  Drew   25

In [223]:
df.to_csv('files/f3.csv', index=False, header=True, sep='\t')
df

Name  Age
0  Amit   20
1  Cody   21
2  Drew   25

In [227]:
# df.to_csv('files/f3.csv', index=False, header=True, sep='_')
df.to_csv('files/f3.csv', index=False, header=True, sep=',')
# df.to_csv('files/f3.csv', index=False, header=True, sep='|')


In [231]:
new_df=pd.read_csv('files/f3.csv',sep=',')
new_df

Name  Age
0  Amit   20
1  Cody   21
2  Drew   25

In [233]:
scores = {'Name': ['a', 'b', 'c', 'd'],
		'Score': [90, 80, 95, 20]}
df=pd.DataFrame(scores)
df

Name  Score
0    a     90
1    b     80
2    c     95
3    d     20

encoding='utf-8'
  to save the file in same format

In [235]:
df.to_csv('files/f4.csv', sep=',', index=False, encoding='utf-8')
df

Name  Score
0    a     90
1    b     80
2    c     95
3    d     20

In [ ]:
path='files/f4.csv'
with open(path,'r') as f:
    x=f.read()
    print(x)

Name,Score
a,90
b,80
c,95
d,20



In [238]:
df.to_csv('files/f4.csv',columns=['Name'],index=False,header=True)

In [240]:
df3= pd.read_csv('files/f4.csv')
df3

Name
0    a
1    b
2    c
3    d

## **Json file**

#### json.dumps
   - used to save data in json format
#### json.loads
   - used o load json data

In [242]:
import json
from io import StringIO

data = {
	"One": {
		"0": 60,
		"1": 60,
		"2": 60,
		"3": 45,
		"4": 45,
		"5": 60
	},
	"Two": {
		"0": 110,
		"1": 117,
		"2": 103,
		"3": 109,
		"4": 117,
		"5": 102
	}
}
df= pd.DataFrame(data)
df

One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102

In [244]:
json_str=json.dumps(data)
json_str

'{"One": {"0": 60, "1": 60, "2": 60, "3": 45, "4": 45, "5": 60}, "Two": {"0": 110, "1": 117, "2": 103, "3": 109, "4": 117, "5": 102}}'

#### **StringIO is used to read json file from string in which data is saved in json format**

In [246]:
df_json = pd.read_json(StringIO(json_str), orient='index')
df_json

0    1    2    3    4    5
One   60   60   60   45   45   60
Two  110  117  103  109  117  102

## **pd.json_normalize( )**

In [248]:
json_data=json.dumps(data)

normalized_json= pd.json_normalize(json.loads(json_data))
print(normalized_json.to_string())

   One.0  One.1  One.2  One.3  One.4  One.5  Two.0  Two.1  Two.2  Two.3  Two.4  Two.5
0     60     60     60     45     45     60    110    117    103    109    117    102


In [250]:
df1=pd.DataFrame(df_json)
df1

0    1    2    3    4    5
One   60   60   60   45   45   60
Two  110  117  103  109  117  102

In [252]:
df2=pd.DataFrame(data)
df2

One  Two
0   60  110
1   60  117
2   60  103
3   45  109
4   45  117
5   60  102

In [254]:
df3= pd.DataFrame(normalized_json)
df3

One.0  One.1  One.2  One.3  One.4  One.5  Two.0  Two.1  Two.2  Two.3  \
0     60     60     60     45     45     60    110    117    103    109   

   Two.4  Two.5  
0    117    102

### **Creating json file from pandas dataframe**

In [255]:
df = pd.DataFrame(
[
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
],index =['row 1', 'row 2', 'row3'],columns =['col 1', 'col 2', 'col3'])
df

col 1 col 2 col3
row 1     a     b    c
row 2     d     e    f
row3      g     h    i

In [260]:
df.to_json('files/j1.json',orient='index')

In [266]:
df1=pd.read_json('files/j1.json')
df1

row 1 row 2 row3
col 1     a     d    g
col 2     b     e    h
col3      c     f    i

In [276]:
df = pd.DataFrame(data = [['15135', 'Alex', '25 / 4/2014'],
                   ['23515', 'Bob', '26 / 8/2018'],
                   ['31313', 'Martha', '18 / 1/2019'],
                   ['55665', 'Alen', '5 / 5/2020'],
                   ['63513', 'Maria', '9 / 12 / 2020']],
                  columns =['ID', 'NAME', 'DATE OF JOINING'])

df.to_json('files/j2.json', orient='columns')

In [277]:
df2= pd.read_json('files/j2.json',orient='columns')
df2

ID    NAME DATE OF JOINING
0  15135    Alex     25 / 4/2014
1  23515     Bob     26 / 8/2018
2  31313  Martha     18 / 1/2019
3  55665    Alen      5 / 5/2020
4  63513   Maria   9 / 12 / 2020

### **Reading Excel Files**

In [278]:
df= pd.read_excel('files/data.xlsx')

In [279]:
df

names  Marks1     city
0  Abbas      76  karachi
1   Adam      65      lhr
2  Saira      55      glt
3   rida      45     slhr

In [ ]:
sheet1 = pd.read_excel('files/data.xlsx', sheet_name='a')
sheet1

names  Marks1     city
0  Abbas      76  karachi
1   Adam      65      lhr
2  Saira      55      glt
3   rida      45     slhr

In [283]:
sheet2 = pd.read_excel('files/data.xlsx', sheet_name='b')

In [286]:
merged= pd.merge(sheet1,sheet2)
merged

names  Marks1     city  Marks2  Age     Domain
0  Abbas      76  karachi      78   20        phy
1   Adam      65      lhr      89   21  social sc
2  Saira      55      glt      69   22       chem
3   rida      45     slhr      77   20        bio

## **Data Analysing**

In [287]:

data = {'First Score': [100, 90, None, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]
        }

df= pd.DataFrame(data)

In [288]:
missing_values=df.isnull()

In [289]:
print(missing_values)

   First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False


In [298]:
data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}

df= pd.DataFrame(data)
df

Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
2  Alice   25       NY
3  David   40  Chicago

#### **removing Duplicate values**

In [299]:
unique=df.drop_duplicates()
unique

Name  Age     City
0  Alice   25       NY
1    Bob   30       LA
3  David   40  Chicago

### **Changing datatype of dataframe**

In [305]:
data = {'Name': ['John', 'Alice', 'Bob', 'Eve', 'Charlie'], 
        'Age': [25, 30, 22, 35, 28], 
        'Gender': ['1', '0', '1', '0', '1'], 
        'Salary': [50000, 55000, 40000, 70000, 48000]}

df = pd.DataFrame(data)
print(df)
df.dtypes


      Name  Age Gender  Salary
0     John   25      1   50000
1    Alice   30      0   55000
2      Bob   22      1   40000
3      Eve   35      0   70000
4  Charlie   28      1   48000


Name      object
Age        int64
Gender    object
Salary     int64
dtype: object

In [308]:
df['Age']=df['Age'].astype(str)
df['Age']=df['Age'].astype(str)
df['Salary']=df['Salary'].astype(float)

In [309]:
df['Join Date'] = ['2021-01-01', '2020-05-22', '2022-03-15', '2021-07-30', '2020-11-11']


In [310]:
df['Join Date']=pd.to_datetime(df['Join Date'])
df

Name Age Gender   Salary  Join Date
0     John  25      1  50000.0 2021-01-01
1    Alice  30      0  55000.0 2020-05-22
2      Bob  22      1  40000.0 2022-03-15
3      Eve  35      0  70000.0 2021-07-30
4  Charlie  28      1  48000.0 2020-11-11

### **Changing multiple column datatype**

In [313]:
df = df.astype({'Age':'int','Salary':'str'})
df.dtypes

Name                 object
Age                   int32
Gender               object
Salary               object
Join Date    datetime64[ns]
dtype: object

### **handling null values**

In [314]:
df = pd.DataFrame({'FirstName': ['Vipul', 'Ashish', 'Milan'], 
                            "Gender": ["", "", ""], 
                            "Age": [0, 0, 0]}) 

df["Department"]= np.nan
df

FirstName Gender  Age  Department
0     Vipul           0         NaN
1    Ashish           0         NaN
2     Milan           0         NaN

In [315]:
df.isna().sum()

FirstName     0
Gender        0
Age           0
Department    3
dtype: int64

In [316]:
df.dropna(how='all', axis=1, inplace=True)
df

FirstName Gender  Age
0     Vipul           0
1    Ashish           0
2     Milan           0

### **Handling empty spaces** 
  - to handle empty space first we replce empty space with nan values and the remove it
  - df.replace( ) is used to replace empty space with nan value

In [317]:
nan_values=float('NaN')
df.replace("",nan_values, inplace=True)
df

FirstName  Gender  Age
0     Vipul     NaN    0
1    Ashish     NaN    0
2     Milan     NaN    0

In [318]:
df.dropna(how='all', axis=1, inplace=True)
df

FirstName  Age
0     Vipul    0
1    Ashish    0
2     Milan    0

#### **replacing zero with nan values and then remoe it**

In [319]:
df.replace(0,np.nan, inplace=True)
df

FirstName  Age
0     Vipul  NaN
1    Ashish  NaN
2     Milan  NaN

In [320]:
df.dropna(how='all', axis=1, inplace=True)
df

FirstName
0     Vipul
1    Ashish
2     Milan