In [28]:

#  including python, modules, universal functions, numpy and pandas. Test will be of both objective and question


In [29]:
# basic operation


num1=int(input("Enter first number: "))
num2=int(input("Enter second number: "))

print("Select operation")
print("1. Addition")
print("2. Subtraction")
print("3. multiplication")
print("4. division")
print("5. Modulo")

op=int(input("Enter operation number"))
print(" You choose: ",op)
if op == 1:
    print(f"{num1} + {num2}: ",num1 + num2)
elif op==2:
    print(f"{num1} - {num2}: ",num1 - num2)
elif op == 3:
   print( f"{num1} * {num2}: ",num1 * num2)
elif op == 4:
    print(f"{num1} / {num2}: ",num1 / num2)
elif op == 5:
    print(f"{num1} % {num2}: ",num1 % num2)
else:
    print("You entered invalid operator:( ")



ValueError: invalid literal for int() with base 10: '66\\'

In [ ]:
# strings

str1="Hello there!"


# indexing and Slicing

print(str1[2:6])
print(str1[0])
print(str1[-1])
print(str1[:])
print(str1[:5])
print(str1[3:])
print(str1[2:-2])

llo 
H
!
Hello there!
Hello
lo there!
llo ther


In [ ]:
str2="Ths is@#a$%6practics session"

print(str2[2:13:2]) #start : end : step

print(str2[::-1]) #start : End : last index

si@a%p
noisses scitcarp6%$a#@si shT


In [ ]:
# string functions
str2="   Ths is practics session   "
str3="This is our AI Class"
print(str2.upper())
print(str2.capitalize())
print(str2.lower())
print(str2.strip())
print(str2.replace("session","class"))
print("count c: ",str2.count("c"))
print("index of p: ",str2.find("p"))
print("Return True if string start with (i) else false: ",str3.startswith('i'))
print("Return True if string start with (T) else false: ",str3.startswith('T'))
print("Return True if string ends with (Class) else false: ",str3.endswith('Class'))
print("Return True if string ends with (Class) else false: ",str3.endswith('session'))
new_str=str3.split(" ")
print(new_str)
print(len(new_str))
print('-'.join(str3.split(" ")))
print('__'.join(str3.split(" ")))

   THS IS PRACTICS SESSION   
   ths is practics session   
   ths is practics session   
Ths is practics session
   Ths is practics class   
count c:  2
index of p:  10
Return True if string start with (i) else false:  False
Return True if string start with (T) else false:  True
Return True if string ends with (Class) else false:  True
Return True if string ends with (Class) else false:  False
['This', 'is', 'our', 'AI', 'Class']
5
This-is-our-AI-Class
This__is__our__AI__Class


In [ ]:
# string formatting
name="Atiqa"
Age="20"

print(f" name: {name} Age is {Age}")


 name: Atiqa Age is 20


In [ ]:
s = "Python"
print(s[::-2])

nhy


In [ ]:
list1=[2,4,6,23,"Atiqa",True,3.45,4-3]

# list indexing and sliciing

print(list1[4])
print(list1[:])
print(list1[3:6])
print(list1[:5])
print(list1[7:])
print(list1[::2])
print(list1[::-1])  #reverse string
print(list1[::-2])

Atiqa
[2, 4, 6, 23, 'Atiqa', True, 3.45, 1]
[23, 'Atiqa', True]
[2, 4, 6, 23, 'Atiqa']
[1]
[2, 6, 'Atiqa', 3.45]
[1, 3.45, True, 'Atiqa', 23, 6, 4, 2]
[1, True, 23, 4]


In [ ]:
list2=["Ahmed","Sara","Raza","Ali","Atiqa","Ayesha","Zain","Zara"]

# list functions

list2.append("zia")
print(list2)

list2[5]="Ayesha Akbar"
print(list2)
list2.insert(2,"Kulsoom")
print(list2)
list2.remove("Sara")
print(list2)
list2.pop()
print(list2)
list2.pop(0)
print(list2)

['Ahmed', 'Sara', 'Raza', 'Ali', 'Atiqa', 'Ayesha', 'Zain', 'Zara', 'zia']
['Ahmed', 'Sara', 'Raza', 'Ali', 'Atiqa', 'Ayesha Akbar', 'Zain', 'Zara', 'zia']
['Ahmed', 'Sara', 'Kulsoom', 'Raza', 'Ali', 'Atiqa', 'Ayesha Akbar', 'Zain', 'Zara', 'zia']
['Ahmed', 'Kulsoom', 'Raza', 'Ali', 'Atiqa', 'Ayesha Akbar', 'Zain', 'Zara', 'zia']
['Ahmed', 'Kulsoom', 'Raza', 'Ali', 'Atiqa', 'Ayesha Akbar', 'Zain', 'Zara']
['Kulsoom', 'Raza', 'Ali', 'Atiqa', 'Ayesha Akbar', 'Zain', 'Zara']


In [ ]:
# list operations

list3=[2,4,6,8,10]
list4=[1,3,5,7,9]

print(list3 + list4) # join lists
print(list3 * 2)

print(12 in list3)
print("Atiqa" in list2)
print("length of list: ",len(list2))
print("length of list: ",len(list3))

[2, 4, 6, 8, 10, 1, 3, 5, 7, 9]
[2, 4, 6, 8, 10, 2, 4, 6, 8, 10]
False
True
length of list:  7
length of list:  5


In [ ]:
list4=[3,0,7,-3,5,1,9]
list4.sort(reverse=True)
print(list4)


[9, 7, 5, 3, 1, 0, -3]


In [ ]:
list5=list4.copy()
list5.append("Nums")
print(list5)
print(list4)

[9, 7, 5, 3, 1, 0, -3, 'Nums']
[9, 7, 5, 3, 1, 0, -3]


In [ ]:
for element in list4:
    print(element**2)

squares= [x**2 for x in range(1,11)]
print(squares)
y=5
table=[x*y for x in range(1,11)]
print(table)

evens=[x for x in range(1,30) if x%2==0]
print(evens)

81
49
25
9
1
0
9
[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]
[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]
[2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28]


In [ ]:
names=["Ahmed","Sara","Raza","Ali","Atiqa","Ayesha","Zain","Zara"]

for name in names:
    print(name)


Ahmed
Sara
Raza
Ali
Atiqa
Ayesha
Zain
Zara


In [ ]:

for name in range(1, len(names)):
    print(f"{name}. {names[name]}")

1. Sara
2. Raza
3. Ali
4. Atiqa
5. Ayesha
6. Zain
7. Zara


In [ ]:
for index,name in enumerate(names):
    print(f"{index}. {name}")

0. Ahmed
1. Sara
2. Raza
3. Ali
4. Atiqa
5. Ayesha
6. Zain
7. Zara


In [ ]:
# # while loop

i=0
while i< len(names):
    print(i,names[i])
    i=i+1



0 Ahmed
1 Sara
2 Raza
3 Ali
4 Atiqa
5 Ayesha
6 Zain
7 Zara


In [ ]:
i=0
names=["Ahmed","Sara","Raza","Ali","Atiqa","Ayesha","Zain","Zara"]


while i< len(names):
   
    if names[i].startswith("Z"):
     print(i,names[i])
    i=i+1

6 Zain
7 Zara


In [ ]:

names=["Ahmed","Sara","Raza","Ali","Atiqa","Ayesha","Zain","Zara"]
i=0
while i < len(names):
    if not names[i].startswith("A"):
        print(names[i])
    i=i+1



Sara
Raza
Zain
Zara


In [ ]:
i=len(names)-1
while i >= 0:
    if names[i].startswith("A"):
        print(names[i])

    i=i-1

Ayesha
Atiqa
Ali
Ahmed


In [ ]:
list1=[1,2,3]
list2=[4,5,6]
list1.extend(list2)
print(list1)# (List1 me List2 ke elements add karna)
print(list2)

list1=[1,2,3]
list2=[4,5,6]
print(list1+list2)
print(list1)

[1, 2, 3, 4, 5, 6]
[4, 5, 6]
[1, 2, 3, 4, 5, 6]
[1, 2, 3]


In [ ]:
matrix = [
    [1, 2, 3],  # Row 0
    [4, 5, 6],  # Row 1
    [7, 8, 9]   # Row 2
]
print(matrix[0][2])
print("-----------------")
first_column = [row[0] for row in matrix]
print(first_column) 

3
-----------------
[1, 4, 7]


In [ ]:
for row in matrix:
    print(row[2])

3
6
9


In [ ]:
for row in matrix:
    for col in row:
        print(col, end=" ")
    print()  

1 2 3 
4 5 6 
7 8 9 


In [ ]:
# Dictionaries

dict1={
    "name":"Atiqa",
    "Domain":"AI",
    "Age": 21,
    "maks":"100"
}


print(dict1)
print(dict1["Age"])
print(dict1["Domain"])
print(dict1["name"],["Age"])

{'name': 'Atiqa', 'Domain': 'AI', 'Age': 21, 'maks': '100'}
21
AI
Atiqa ['Age']


In [ ]:
print(dict1.get("Interest","Not found"))

Not found


In [ ]:
dict1["Age"]=22
print(dict1)

dict1["Qualification"]= "BS"
print(dict1)

del dict1["maks"]
print(dict1)

{'name': 'Atiqa', 'Domain': 'AI', 'Age': 22, 'maks': '100', 'Qualification': 'BS'}
{'name': 'Atiqa', 'Domain': 'AI', 'Age': 22, 'maks': '100', 'Qualification': 'BS'}
{'name': 'Atiqa', 'Domain': 'AI', 'Age': 22, 'Qualification': 'BS'}


In [ ]:


dict1={
    "name":"Atiqa",
    "Domain":"AI",
    "Age": 21,
    "maks":"100"
}

age=dict1.pop("Age")
print(age)


21


In [ ]:

dict1={
    "name":"Atiqa",
    "Domain":"AI",
    "Age": 21,
    "maks":"100"
}
for keys,values in dict1.items():
    print(f"{keys}: {values}")

name: Atiqa
Domain: AI
Age: 21
maks: 100


In [ ]:
for values in dict1.values():
    print(f" {values}")

print("-----------------------")
for keys,values in dict1.items():
    print(f"{keys} {values}")

 Atiqa
 AI
 21
 100
-----------------------
name Atiqa
Domain AI
Age 21
maks 100


In [ ]:
if "interest" in dict1:
    print("Your interest exist")
else:
    print("not exist")

print("-----------------------")

if "name" in dict1:
    print("Your name exist")
else:
    print("not exist")

not exist
-----------------------
Your name exist


In [ ]:
students={
"Ali":{"Age":20,"marks":90},
"Sana":{"Age":22,"marks":96},
"Rafi":{"Age":21,"marks":89},
"Sohail":{"Age":21,"marks":86},
}

In [ ]:
print(students["Sana"]["marks"])

96


In [ ]:
for name,details in students.items():
        print(f"{name}\n Details: Age:{details["Age"]} Marks: {details['marks']}")


Ali
 Details: Age:20 Marks: 90
Sana
 Details: Age:22 Marks: 96
Rafi
 Details: Age:21 Marks: 89
Sohail
 Details: Age:21 Marks: 86


In [ ]:
# functions

def func1():
    print("Hello there")

In [ ]:
func1()

Hello there


In [ ]:
def func1(name):
    print(f"Hello {name}")

func1("neha")
name="Rahul"
func1(name)

Hello neha
Hello Rahul


In [ ]:
def func1(a,b):
    return a+b


func1(3,6)

9

In [ ]:
def func1(a=4,b=3):
 print(a+b)


func1(b=1)
func1(2,2)
func1(7)

5
4
10


In [ ]:
def add(*nums):
    return sum(nums)

In [ ]:
print(add(3,5))

8


In [ ]:
def details(**info):
    for keys,values in info.items():
        print(f"{keys} value: {values}")


print(details(name="Atiqa"))

name value: Atiqa
None


In [ ]:
# lambda function

square= lambda x:x*x
print(square(2))
print(square(12))

cube=lambda x: x*x*x
print(cube(3))

4
144
27


In [ ]:
def func(fx,a):
    n=fx+3+a
    print(n)

func(cube(3),5)

35


In [ ]:
add=lambda a,b:a+b

print(add(2,4))

6


In [ ]:
# nested function 

def out(x,y):
 def inner(x,y):
    return x+y
 return inner(x,y) + 5

print(out(2,1))

8


In [ ]:
def fact(n):
    if n==1:
        return 1
    return n* fact(n-1)

fact(5)

120

In [ ]:
# Exception handling:

try:
    a=23
    b=0
    print("Division: ",a/b)
except Exception as e:
    print(e)
print("==================")
try:
    a=23
    b=0
    print("Division: ",a/b)
except ZeroDivisionError:
    print("Unable to divide number with 0")



division by zero
Unable to divide number with 0


In [ ]:
try:
    num=int(input("Enter number: "))

except Exception as e:
    print(e)


invalid literal for int() with base 10: 'gdh'


In [ ]:
try:
    a=10
    num=int(input("Enter number: "))
    print(a/num)

except ZeroDivisionError:
    print("Denominator cant be zero")
except ValueError:
    print("Invalid value entered")
except Exception as e:
    print(e)

Invalid value entered


In [ ]:
num=int(input("Enter number from 5, 10 ,15"))
if num not in [5,10,15]:
    raise ValueError("Please select the number as per instrctions")
print(num*num)


225


In [ ]:
# Object oriented programming 
class Student:
    def __init__(self,name,age):
        self.name=name
        self.age=age

    def info(self):
        print(f"Name:{self.name} Age:{self.age}")

s1=Student("Anam",21)
s1.info()
s2=Student("Atiqa",20)
s2.info()

Name:Anam Age:21
Name:Atiqa Age:20


In [ ]:
class Car:
    model="Rx154E"
    color="Purple"
    no_plate="1201"


c1=Car()
print(c1.model)
print(Car.color)
c1.no_plate="3225"
print(c1.no_plate)

Rx154E
Purple
3225


In [ ]:
class Person: #--> class 
    name="Richerd"
    occuption="Software Enginner"
    salary=3000

In [ ]:
p1=Person() #--> object
p1.occuption="DevOps Engineer"
print("\n",p1.name," is a ",p1.occuption,"\n")

p2=Person() #--> object
p2.name="Neil"
print("\n",p2.name," is a ",p2.occuption,"\n")



 Richerd  is a  DevOps Engineer 


 Neil  is a  Software Enginner 



In [ ]:
# Encapsulation

class Account:
     def __init__(self, account_holder):
          self.account_holder=account_holder
          self.__balance=10000  #private

     def deposit(self,amount):
          self.__balance=self.__balance+amount
          print("Deposit successful")

     def withdrawl(self,amount):
          if (self.__balance >= amount):
               self.__balance=self.__balance-amount
               print("Withdrawl Successfully")
          else:
               print("Your current balance is Insufficient")


     def get_balance(self):
          print(f"Account Holder:{self.account_holder} Current balance: {self.__balance}")       
          

In [ ]:
a1=Account("Atiqa")
a1.get_balance()
a1.deposit(5000)
a1.get_balance()
a1.withdrawl(12000)
a1.get_balance()
a1.withdrawl(5000)

Account Holder:Atiqa Current balance: 10000
Deposit successful
Account Holder:Atiqa Current balance: 15000
Withdrawl Successfully
Account Holder:Atiqa Current balance: 3000
Your current balance is Insufficient


In [ ]:
# Abstraction
from abc import ABC,abstractmethod

class Animal(ABC):
    @abstractmethod
    def sound(self):
        pass

class Dog(Animal):
    def sound(self):
        print("Barks")


class Cat(Animal):
    def sound(self):
        print("Meow")


Meow


In [ ]:
c1=Cat()
c1.sound()

d1=Dog()
d1.sound()

Meow
Barks


In [ ]:
# inheritance

class Vechical:
    def __init__(self,brand):
        self.brand=brand

    def show_brand(self):
        print(f"Brand: {self.brand}")

class Car(Vechical):
    def __init__(self, brand,model):
        super().__init__(brand)
        self.model=model

    
    def show_model(self):
        print(f"Model: {self.model}")

# v1=Vechical("SUZUKI")
# v1.show_brand()

c1=Car("SUZUKI","RX31ZE")
c1.show_brand()
c1.show_model()




Brand: SUZUKI
Model: RX31ZE


In [ ]:
class Person:
    def __init__(self,name,age):
        self.name=name
        self.age=age

    def info(self):
        print(f"Name: {self.name} Age: {self.age}")


class Student(Person):
    def __init__(self, name, age,marks):
        super().__init__(name, age)
        self.marks=marks

    def info(self):
        super().info()
        print(f"marks: {self.marks}")


In [ ]:

s1=Student("Atiqa",21,90)
s1.info()

Name: Atiqa Age: 21
marks: 90


In [ ]:
class Animal:
    def sound(self):
        print("Animals can make sound: ")

class Dog(Animal):
    def sound(self):
        print("Barks")

class Cat(Animal):
    def sound(self):
        print("Meow")


In [ ]:
animals=[Dog(),Cat()]
for animal in animals:
    animal.sound()

Barks
Meow


In [ ]:
# modules

import math as m

In [ ]:
print(m.sqrt(25))

5.0


In [ ]:
print(m.ceil(4.3))
print(m.floor(4.3))
print(m.floor(-4.3))
print(m.ceil(-4.9))

5
4
-5
-4


In [ ]:
import time

In [ ]:
x1=time.time()
for i in range(5000):
    for j in range(i):
        i*j
x2=time.time()

print(x2-x1)

0.8744847774505615


In [ ]:
print("Hello")
x1=time.time()
names=["ali","Sana","rani","salar"]
for name in names:
   time.sleep(3)
   print(name)

x2=time.time()
print(x2-x1)

Hello
ali
Sana
rani
salar
12.002906799316406


In [ ]:
print(time.ctime(time.time()))

Sun Feb 16 23:33:09 2025


In [ ]:
print(time.strftime("%Y-%m-%d %H:%M:%S %p"))
print(time.strftime("%a %b %y"))


2025-02-16 23:43:06 PM
Sun Feb 25


In [ ]:
time.localtime()

time.struct_time(tm_year=2025, tm_mon=2, tm_mday=16, tm_hour=23, tm_min=46, tm_sec=48, tm_wday=6, tm_yday=47, tm_isdst=0)

In [ ]:
from datetime import datetime

In [ ]:
date1 = "2024-02-10"
date2 = "2025-02-12"

d1=datetime.strptime(date1,"%Y-%m-%d")
d2=datetime.strptime(date2,"%Y-%m-%d")

In [ ]:
print(d2-d1)

368 days, 0:00:00


In [ ]:
import time
formatted=time.strftime("%Y-%m-%d",time.localtime())
print(formatted)

formatted=time.strftime("%Y-%m-%d")
print(formatted)

current_time=time.localtime()
print (current_time)

2025-02-17
2025-02-17
time.struct_time(tm_year=2025, tm_mon=2, tm_mday=17, tm_hour=7, tm_min=22, tm_sec=48, tm_wday=0, tm_yday=48, tm_isdst=0)


In [ ]:
t1=time.monotonic()
for i in range(5000):
    for j in range(i):
        i+j

t2=time.monotonic()
t=t2-t1
print(f"time: {t:.6f}")

time: 2.313000


In [ ]:
t=time.time()
print(time.strftime("%Y-%m-%d"))
print(time.ctime(t))


2025-02-17
Mon Feb 17 07:31:43 2025


In [ ]:
import time

start = time.perf_counter()  # Start
time.sleep(2)  # Simulate delay
end = time.perf_counter()  # End

print("Execution Time:", end - start, "seconds")


Execution Time: 2.0014455000055023 seconds


In [ ]:
import time
print("Time Zone:", time.tzname)

Time Zone: ('Pakistan Standard Time', 'Pakistan Daylight Time')


In [32]:
# file handlinng

file=open("test","r")
print(file.read())
file.close()


hello
1 Ahmed
2 Alice
3 Raza


In [35]:
file=open("Test1",'r')
text=file.read(10)
print(text)
file.close()

here we ha


In [67]:
file=open("test.txt","r")
text=file.readlines()
file.close()
for i in text:
  if i==5:
     continue
  print(i)

line1

line2

line3

line4

line5

line6

line7



In [70]:
file=open("test3",'w')
text='''Players start on the same randomly selected article, and must navigate to another pre-selected target article, solely by clicking links within each article. The goal is to arrive at the target article in the fewest clicks (articles), or the least time.

Players or an impartial overseer (i.e. referee) choose the start and end pages. If you are playing for number of clicks, a close tally must be kept of the number of clicks used by a player; all selections must be accounted for. Whoever has the fewest clicks wins. The browser history can be used to determine number of articles / clicks. A round in the Wiki Game can be played at one computer terminal, where players take turns, or at multiple computers simultaneously. In the latter option, a "session" begins immediately after everyone loads their randomized Starting Page and ends when the last person returns to their Homing Page. The game can also be played by seeing who can get to the designated page first, regardless of the number of clicks'''

file.write(text)
file.close()

In [81]:
file=open('test3','r+')
text=file.readline(100)
file.close()

In [ ]:
print(len(text))
# text1=text.__str__.split(" ")
file=open("new file.txt",'w')
file.writelines(text)
file.close()

15


In [91]:
file = open("example.txt", "w")  
lines = ["Line 1\n", "Line 2\n", "Line 3\n"]  
file.writelines(lines)  
file.close()

In [95]:
import os
if os.path.exists("mytest"):
    os.remove("mytest")
    print("File Deleted")

else:
    print("File not exist")

File not exist


In [96]:
with open('test','r') as f:
    text=f.read()
    print(text)


hello
1 Ahmed
2 Alice
3 Raza


In [97]:
with open("test",'w') as f:
    f.write("jsdkfnbc dchjkevr veliffh cmndmsfee fv udfdfv duyf fvvfhveevfeeurvf")
    

In [101]:
import os
list=["line1\n","line2\n","line3\n","line4\n","line5\n","line6\n","line7\n",]
with open("test.txt","w") as f:
    f.writelines(list)
    # f.close()
    

with open("test.txt") as f:
    lines=f.readlines()
    print(lines)

['line1\n', 'line2\n', 'line3\n', 'line4\n', 'line5\n', 'line6\n', 'line7\n']


In [102]:
# with open("test.txt") as f:
#     lines=f.readlines()
#     print(lines)
with open("new_file.txt","w") as fp:
    for i,line in enumerate(lines):
        if i==4:
            continue
        fp.writelines(line)
        

In [1]:
import custom as c


In [2]:
c.greet("Atiqa")

Hello Atiqa. Welcome to our class


In [ ]:
c.add(1,6)

7

In [2]:
import custom as c

In [3]:
s1=c.Student("Atiqa",21,90)

In [4]:
s1.info()

Student Name: Atiqa, Age: 21, Marks: 90


In [5]:
import shutil

In [6]:
shutil.copy("test","new1")

'new1'

In [7]:
shutil.copy2("test","new1")

'new1'

In [2]:
# numpy

import numpy as np

In [ ]:
arr=np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [6]:
arr=np.array(4)
print(np.ndim(arr))

0


In [17]:
arr=np.array([2,6,7], ndmin=5)
print(np.ndim(arr))
print(arr)
print(arr[0][0][0][0][::-1])

5
[[[[[2 6 7]]]]]
[7 6 2]


In [20]:
print(arr.ndim)
print(arr.nbytes)
print(arr.size)
print(arr.shape)

5
12
3
(1, 1, 1, 1, 3)


In [31]:
arr=np.array([[1,2,9,7,3],[4,5,2,77,6]])
print(arr[::])


[[ 1  2  9  7  3]
 [ 4  5  2 77  6]]


In [32]:
print(arr[1,3])

77


In [41]:
print(arr[-1::])

[[ 4  5  2 77  6]]


In [44]:
print(arr[1,::-1])
print(arr[:,::-1])


[ 6 77  2  5  4]
[[ 3  7  9  2  1]
 [ 6 77  2  5  4]]


In [47]:
print(arr[::-1,:])


[[ 4  5  2 77  6]
 [ 1  2  9  7  3]]


In [53]:
arr=np.array([[[1,2,0,0,3],[4,1,2,1,0]],[[9,2,5,8,2],[4,5,2,1,6]]])
arr

array([[[1, 2, 0, 0, 3],
        [4, 1, 2, 1, 0]],

       [[9, 2, 5, 8, 2],
        [4, 5, 2, 1, 6]]])

In [57]:
print(arr[::-1,::-1,::-1])

[[[6 1 2 5 4]
  [2 8 5 2 9]]

 [[0 1 2 1 4]
  [3 0 0 2 1]]]


In [ ]:
arr=np.array([[1,2,3,4,5],[6,7,8,9,0]])
print(arr[1,2])

8


In [59]:
arr=np.array([[[1,2,3,4,5],[6,7,8,9,0]],[[11,12,13,14,15],[16,17,18,19,20]]])
print(arr[1,1,4])

20


In [60]:
arr=np.array([[1, 2, 3], [4, 5, 6]])
print(arr[::-1,::-1])
print("-"*20)
print(arr[:,::-1])
print("-"*20)

[[6 5 4]
 [3 2 1]]
--------------------
[[3 2 1]
 [6 5 4]]
--------------------


In [61]:
arr=np.arange(0,20,2)   #make an array of all even numbers
print(arr)
arr=np.arange(1,20,2)   #make an array of all odd numbers
print(arr)

[ 0  2  4  6  8 10 12 14 16 18]
[ 1  3  5  7  9 11 13 15 17 19]


In [62]:
arr1=np.array([1,2,6,4])
arr2=np.array([5,2,4,8])
print(arr1+arr2)
print(arr1*arr2)
print(arr1-arr2)
print(arr1/arr2)
print(arr1%arr2)

[ 6  4 10 12]
[ 5  4 24 32]
[-4  0  2 -4]
[0.2 1.  1.5 0.5]
[1 0 2 4]


In [73]:
arr=np.array([1,2,3,4,5,5,9,0,6])

even=0
odd=0
for i in range(len(arr)):
    if arr[i]%2==0:
        even=even+arr[i]
    else:
        odd=odd+arr[i]

print("Sum even",even)
print("Sum odd",odd)


Sum even 12
Sum odd 23


In [79]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

print(arr[2,1])

8


In [85]:
arr = np.array([10, 20, 30, 40, 50, 60, 70])

print(arr[2:5])
print(arr[::2])
print(arr[::-1])
print(arr[:2])
print(arr[2:])
print(arr[-1])

[30 40 50]
[10 30 50 70]
[70 60 50 40 30 20 10]
[10 20]
[30 40 50 60 70]
70


In [87]:
arr = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [91]:
print(arr[:])
print(arr[:,1])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 2  6 10]


In [92]:
print(arr[0:2, 1:3])  

[[2 3]
 [6 7]]


In [95]:
print(arr[:, 2])
print(arr[1, :])

[ 3  7 11]
[5 6 7 8]


In [99]:
arr=np.array([2,34,56,87,232,3])

filter=arr%2==0
print(filter)
print(arr[filter])

arr=np.array([2,34,56,87,232,3])

filter=arr%2!=0
print(filter)
print(arr[filter])

[ True  True  True False  True False]
[  2  34  56 232]
[False False False  True False  True]
[87  3]


In [100]:
arr=np.array([[[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]]])
for layer in arr:
    for row in layer:
        for element in row:
            print(element)


1
2
3
4
5
6
7
9
11
12
13
15


In [101]:
arr=np.array([[[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]]])
for layer in arr:
    for row in layer:
        
            print(row)

[1 2 3]
[4 5 6]
[ 7  9 11]
[12 13 15]


In [102]:
for i in np.nditer(arr):
    print(i*2)

2
4
6
8
10
12
14
18
22
24
26
30


In [106]:
arr=np.array([[[ 1 , 2 , 3],[ 4 , 5 , 6],[ 7 , 9, 11],[12 ,13 ,15]]])
new=arr.astype("S")
print(type(new))
for i in np.nditer(new):
    print(i)
for i in np.nditer(arr):
    print(i)

<class 'numpy.ndarray'>
b'1'
b'2'
b'3'
b'4'
b'5'
b'6'
b'7'
b'9'
b'11'
b'12'
b'13'
b'15'
1
2
3
4
5
6
7
9
11
12
13
15


In [109]:
# pandas
import pandas as pd

mydata={
    "names":["Sara","Ahmed","Seema","Fatima"],
    "marks1":[64,57,43,67],
    "marks2":[76,78,85,97]
}

df=pd.DataFrame(mydata)
print(df)

    names  marks1  marks2
0    Sara      64      76
1   Ahmed      57      78
2   Seema      43      85
3  Fatima      67      97


In [115]:
print(df["names"])
print(df["marks1"])


0      Sara
1     Ahmed
2     Seema
3    Fatima
Name: names, dtype: object
0    64
1    57
2    43
3    67
Name: marks1, dtype: int64


In [117]:
a=[1,2,3,4,5]
index_lable=['a','b','c','d','e']
anss=pd.Series(a, index=index_lable)
print(anss)
print(anss.loc['d'])
print(anss.loc['a'])

a    1
b    2
c    3
d    4
e    5
dtype: int64
4
1


In [125]:
a=["apple","banana","mango"]
ser=pd.Series(a,index=("a",'b','c'))
print(ser)


a     apple
b    banana
c     mango
dtype: object


In [130]:
print(ser.loc['b'])

banana


In [134]:
a=["apple","banana","mango"]
ser=pd.Series(a,index=(1,2,3))
print(ser)
print(ser.loc[1])
print(ser.iloc[1])

1     apple
2    banana
3     mango
dtype: object
apple
banana
