In [1]:
import numpy as np
# import random

In [2]:
arr = np.array([3,45,67,34,2]) #----> this will create an array of one dimensional

In [3]:
print(arr)

[ 3 45 67 34  2]


In [4]:
array_zero=np.zeros(5)
array_one=np.ones(5)

In [5]:
print(array_zero)
print(array_one)

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [6]:
# Mathematical operations 

arr1=np.array([3,5,8,2,1,9])
arr2=np.array([1,2,3,4,5,6])

In [7]:
arr3= arr1+arr2
print(arr3)

[ 4  7 11  6  6 15]


In [8]:
mul= arr1*arr2
print(mul)

[ 3 10 24  8  5 54]


In [9]:
print(arr1*2)
print(arr2*3)

[ 6 10 16  4  2 18]
[ 3  6  9 12 15 18]


In [10]:
arr3=np.array([34,2,4,67,21,87])

In [11]:
print("Minimum of all elements: ",min(arr3))
print("Maximum of all elements: ",max(arr3))
print("Sum of all elements: ",sum(arr3))

Minimum of all elements:  2
Maximum of all elements:  87
Sum of all elements:  215


In [12]:
random_numbers=np.random.rand(5)
print(random_numbers)

[0.59985027 0.11973397 0.98538216 0.46862678 0.17674972]


In [13]:
arr=np.array([2,34,8,5,6],)

In [14]:
arr=[1,2,3,4,5,32,45,56]
new_list=[x + 10 for x in arr ]

In [15]:
print(new_list)

[11, 12, 13, 14, 15, 42, 55, 66]


In [16]:
list1=[x % 2 for x in arr]
print(list1)

[1, 0, 1, 0, 1, 0, 1, 0]


In [17]:
even=["even" for x in arr if x%2==0]

In [18]:
print(even)

['even', 'even', 'even', 'even']


In [19]:
arr=np.array([2,3,4,5,6,7,8])
n_arr=arr+5
print(arr)
print(n_arr)


[2 3 4 5 6 7 8]
[ 7  8  9 10 11 12 13]


In [20]:
# multi dimensonal array 
arr=np.array([[1,2,3,4,5],[3,2,4,6,8],[4,6,7,9,5]])
print(arr.shape) #3 rows and 5 columns

(3, 5)


In [21]:
arr=np.zeros((3,2))
print(arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [22]:
arr=np.ones((3,2,5))
# 3 arrays 2 rows 5 columns
print(arr)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [23]:
print(np.random.rand(3)) #----> generate random 3 numbers between 1 and 0
print(np.random.randint(1, 10, (3,4)))  #----> generate random numbers between 1 to 10 and dimension of array wll be 3x4

[0.13293822 0.60043562 0.11868031]
[[8 8 3 6]
 [1 9 2 3]
 [6 2 4 1]]


In [24]:
arr=np.array([1,2,3,4,5,5,6,7,8,9])
print(arr.reshape(5,2))
print()
print(arr.reshape(2,5))

[[1 2]
 [3 4]
 [5 5]
 [6 7]
 [8 9]]

[[1 2 3 4 5]
 [5 6 7 8 9]]


In [25]:
print("Sum: ",np.sum(arr))    # Sum of all elements
print("Avg: ",np.mean(arr))   # Average
print("MAx: ",np.max(arr))    # Maximum value
print("Min: ",np.min(arr))    # Minimum value
print("Sqrt:",np.sqrt(arr))

Sum:  50
Avg:  5.0
MAx:  9
Min:  1
Sqrt: [1.         1.41421356 1.73205081 2.         2.23606798 2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]


In [26]:
# indexing
print(arr[:])

[1 2 3 4 5 5 6 7 8 9]


In [27]:
print(arr[3:7])
print(arr[:6])
print(arr[-1:])
print(arr[3:-3])

[4 5 5 6]
[1 2 3 4 5 5]
[9]
[4 5 5 6]


In [28]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix[1,2])#1 is array index and 2 is arra element index
print() 
print(matrix[:,2]) #include all arrays index and 2 is array element index

6

[3 6]


In [29]:
n_arr=(arr[arr>4])

In [30]:
print(n_arr)
print(arr)

[5 5 6 7 8 9]
[1 2 3 4 5 5 6 7 8 9]


In [31]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1,arr2)))

[1 2 3 4 5 6]


In [32]:
arr = np.array(['Minal', 'Python', 'NumPy'], dtype='U')  # 'U' matlab Unicode string
print(arr)

['Minal' 'Python' 'NumPy']


In [33]:
l=np.char.str_len(arr)

In [34]:
print(l)

[5 6 5]


In [35]:
arr1=np.array(["hello","hi"])
arr2=np.array(["Minal","python"])
arr3=np.char.add(arr1,arr2)
print(arr3)

['helloMinal' 'hipython']


In [36]:
import numpy as np


# -----------> view and copy in numpy
# view-------> refrence of original array
# if any change is made in the view it will be reflected in the original array 

In [93]:
arr=np.array([2,3,5,6,7])
print(arr)
new_arr=arr.view()
new_arr*=2
print(new_arr)

print(arr)
print("Orginal array: ",type(arr))
print("new_arr",type(new_arr))

[2 3 5 6 7]
[ 4  6 10 12 14]
[ 4  6 10 12 14]
Orginal array:  <class 'numpy.ndarray'>
new_arr <class 'numpy.ndarray'>


In [38]:
arr=np.array([3,2,6,6,8,9])

new_arr=arr.copy()
new_arr[3]=13
print(new_arr)
print(arr)
print("Orginal array: ",type(arr))
print("new_arr",type(new_arr))

[ 3  2  6 13  8  9]
[3 2 6 6 8 9]
Orginal array:  <class 'numpy.ndarray'>
new_arr <class 'numpy.ndarray'>


In [39]:
arr=np.array([3,2,6,7,8,9])
new_arr=arr.copy()
new_arr+=3
print(new_arr)
print(arr)
print("Orginal array: ",type(arr))
print("new_arr",type(new_arr))


[ 6  5  9 10 11 12]
[3 2 6 7 8 9]
Orginal array:  <class 'numpy.ndarray'>
new_arr <class 'numpy.ndarray'>


In [40]:
arr=np.array([2,3,4,5,6,1])

new_arr=arr.reshape(2,-1)
print(new_arr)
new_arr=arr.reshape(3,-1)
print(new_arr)
new_arr=arr.reshape(-1)
print(new_arr)

[[2 3 4]
 [5 6 1]]
[[2 3]
 [4 5]
 [6 1]]
[2 3 4 5 6 1]


In [41]:
arr=np.array([[2,4,6],[1,3,5]])
print(arr.reshape(-1))   #-1 will convert array to 1D

[2 4 6 1 3 5]


In [42]:
arr=np.array([[[3,4,5],[8,9,0]],[[1,2,3],[3,8,5]]])

In [43]:
print(arr)
print(arr.ndim)
print("---------------")
print("reshaped")
print(arr.reshape(2,6))
print("---------------")
print("reshaped")
print(arr.reshape(3,4))
print("---------------")
print("reshaped")
print(arr.reshape(4,-1)) #in this -1 iis used as we dont know the columns number
print("---------------")
print("reshaped")
print(arr.reshape(6,-1))


[[[3 4 5]
  [8 9 0]]

 [[1 2 3]
  [3 8 5]]]
3
---------------
reshaped
[[3 4 5 8 9 0]
 [1 2 3 3 8 5]]
---------------
reshaped
[[3 4 5 8]
 [9 0 1 2]
 [3 3 8 5]]
---------------
reshaped
[[3 4 5]
 [8 9 0]
 [1 2 3]
 [3 8 5]]
---------------
reshaped
[[3 4]
 [5 8]
 [9 0]
 [1 2]
 [3 3]
 [8 5]]


In [44]:
import numpy as np
arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
newarr=arr.reshape(2,-1)
print(newarr)
newarr=arr.reshape(5,-1)
print(newarr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [45]:
arr=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr.reshape(-1))
print(arr.reshape(1,-1))
print(arr.reshape(9))

[1 2 3 4 5 6 7 8 9]
[[1 2 3 4 5 6 7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [46]:
arr=np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Original array:\n",arr)
print("Reshaped array:\n",arr.reshape(2,-1))
print("Reshaped array:\n",arr.reshape(-1,2))

Original array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Reshaped array:
 [[1 2 3 4]
 [5 6 7 8]]
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [47]:

arr=np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
print("Original Array\n",arr)
newarr=arr.reshape(2,2,-1)
print("Reshaped array: \n",newarr)

Original Array
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
Reshaped array: 
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [95]:
arr=np.array([1, 2, 3, 4, 5, 6, 7])
newarr=arr.reshape(7,-1)
print(newarr)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


In [97]:
# itreation

arr=np.array([1,3,5,6,7])
for i in range(len(arr)):
    print(arr[i])

1
3
5
6
7


In [50]:
arr=np.array([[1,2,3],[4,5,6]])
# for i in range (len(arr)):
#     print(arr[i]) #-----> iterating each row

for i in arr:
    print(i)


[1 2 3]
[4 5 6]


In [51]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for row in arr:
  for element in row:
    print(element)

1
2
3
4
5
6


In [52]:
arr=np.array([[[1,2,5],[2,5,6]],[[0,8,9],[6,7,8]]])

In [53]:
print(arr)
print("Dimension: ",arr.ndim)
for element in np.nditer(arr):
    print(element)

[[[1 2 5]
  [2 5 6]]

 [[0 8 9]
  [6 7 8]]]
Dimension:  3
1
2
5
2
5
6
0
8
9
6
7
8


In [54]:
for layer in arr:       #---->traditionl method
    for row in layer:
        for element in row:
            print(element)

1
2
5
2
5
6
0
8
9
6
7
8


In [55]:
# ---> ndenumerate
for index, value in np.ndenumerate(arr):
    print(f"Index: {index} Value: {value}")

Index: (0, 0, 0) Value: 1
Index: (0, 0, 1) Value: 2
Index: (0, 0, 2) Value: 5
Index: (0, 1, 0) Value: 2
Index: (0, 1, 1) Value: 5
Index: (0, 1, 2) Value: 6
Index: (1, 0, 0) Value: 0
Index: (1, 0, 1) Value: 8
Index: (1, 0, 2) Value: 9
Index: (1, 1, 0) Value: 6
Index: (1, 1, 1) Value: 7
Index: (1, 1, 2) Value: 8


In [56]:
# -----> order='C' (row-wise) / order='F' (column-wise) 
import numpy as np
arr=np.array([[2,4,0],[1,8,6],[9,4,7]])
for element in np.nditer(arr,order='C'):
    print(element)
print()
for element in np.nditer(arr,order='F'):
    print(element)

2
4
0
1
8
6
9
4
7

2
1
9
4
8
4
0
6
7


In [57]:
# que1
arr=np.array([[5, 10], [15, 20]])
for element in np.nditer(arr):
    print(element*2)

10
20
30
40


In [58]:
arr=np.array([[[1], [2]], [[3], [4]]])
for index,value in np.ndenumerate(arr):
    print(f"Index:{index} value: {value}")

Index:(0, 0, 0) value: 1
Index:(0, 1, 0) value: 2
Index:(1, 0, 0) value: 3
Index:(1, 1, 0) value: 4


In [59]:
arr=np.array([[10, 20], [30, 40]])
print("Row iteration")
for element in np.nditer(arr,order='F'):  #----> column wise iteration
    print(element)
print("Column Iteration")
for element in np.nditer(arr,order='c'):  #----> row wise iteration
    print(element)

Row iteration
10
30
20
40
Column Iteration
10
20
30
40


In [60]:

arr=np.array([1,5,2])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):

    print(x)

#----->  output
# b'1'   --->b= byte string
# b'5'
# b'2'

b'1'
b'5'
b'2'


In [61]:
arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes='S'):
  print(x)
  print(x.dtype)
        

b'1'
|S11
b'2'
|S11
b'3'
|S11


In [62]:
# Step size 
import numpy as np
arr1=np.array([[6,7,8,9,0],[1,2,3,4,5]])
print("dimension: ",arr1.ndim)
print("Shape: ",arr1.shape)
print("Size: ",arr1.size)
print("Type: ",type(arr1))


for x in np.nditer(arr1[0:1,::2]):
    print(f"Datatype: {x}")

dimension:  2
Shape:  (2, 5)
Size:  10
Type:  <class 'numpy.ndarray'>
Datatype: 6
Datatype: 8
Datatype: 0


In [63]:
# joining two arrays

arr1=np.array([[1,2,4,5,6],[3,4,5,6,7]])
arr2=np.array([[1,9,0,2,4],[7,1,0,2,1]])

arr3=np.concatenate((arr1,arr2), axis=1)  # this will concatenate multiple arrays in horizontal (axis=0)
# combine first array of first dimension and second array of second dimension
print(arr3)
print()
arr3=np.concatenate((arr1,arr2), axis=0) # this will concatenate multiple arrays in vertical (axis=1)
# this will stack arrays dimension one after other
print(arr3)


[[1 2 4 5 6 1 9 0 2 4]
 [3 4 5 6 7 7 1 0 2 1]]

[[1 2 4 5 6]
 [3 4 5 6 7]
 [1 9 0 2 4]
 [7 1 0 2 1]]


In [64]:
arr4=arr1+arr2  # ths will add elements of first dimension array to the corresponding
# element of second dimension
print(arr4)

[[ 2 11  4  7 10]
 [10  5  5  8  8]]


In [65]:
# Stack function 

arr1=np.array([4,6,7])
arr2=np.array([1,3,0])

arr=np.stack((arr1, arr2),axis=0)
print(arr)
print()
arr=np.stack((arr2, arr1))
print(arr)
print()
arr=np.stack((arr1, arr2), axis=1) #this will convert rows in to columns or stacked vertically
print(arr)

[[4 6 7]
 [1 3 0]]

[[1 3 0]
 [4 6 7]]

[[4 1]
 [6 3]
 [7 0]]


In [100]:
arr1=np.array([[1,3],[7,4]])
arr2=np.array([[9,0],[8,2]])
arr=np.stack((arr1,arr2)) # stack dimension of both arrays to horizontal direction
print(arr)
print("===================")
#  [1,3] [9,0] and [7,4] [8,2] both the arrays get combined and output wil be [[1 3 9 0][7 4 8 2]]
arr=np.hstack((arr1,arr2)) # stack dimension of both arrays to horizontal direction
print(arr)
print("===================")
arr=np.vstack((arr1,arr2)) # atack all elements in vertical direction first elemeny of all dimension is stacked to first column
print(arr)
print("--------------------")
arr=np.dstack((arr1,arr2)) # stack all elements in that are in  corresponding column of both arrays to row
print(arr)


[[[1 3]
  [7 4]]

 [[9 0]
  [8 2]]]
[[1 3 9 0]
 [7 4 8 2]]
[[1 3]
 [7 4]
 [9 0]
 [8 2]]
--------------------
[[[1 9]
  [3 0]]

 [[7 8]
  [4 2]]]


In [67]:
# Split numpy array 

arr=np.array([2,4,6,8,7,9,0,3,5,6,7,8,2])
print(np.array_split(arr, 3,axis=0))   #split array to unequal elements in each splited array
# print(np.split(arr,3))  split array to equal elements in each splited array

[array([2, 4, 6, 8, 7]), array([9, 0, 3, 5]), array([6, 7, 8, 2])]


In [102]:
import numpy as np
arr = np.array([[1, 2,3, 4, 5,7]])

# Split into 3 sub-arrays along rows
result = np.array_split(arr, 3)
print(result)
print(result[0])
print(result[1])
print(result[2])
# print(result[3])

[array([[1, 2, 3, 4, 5, 7]]), array([], shape=(0, 6), dtype=int32), array([], shape=(0, 6), dtype=int32)]
[[1 2 3 4 5 7]]
[]
[]


In [69]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [70]:
# Serach in array 

# where keyword is used to search a specific element in array 
arr=np.array([2,4,6,8,7,9,0,3,5,6,7,8,2])
x= np.where(arr==8)
print(x)


(array([ 3, 11], dtype=int64),)


In [71]:
# arr=np.array([2,4,6,8,7,9,0,3,5,6,7,8,2])
# x= np.where(arr>5)
# print(x)
# Question 3
# Why is NumPy Faster Than Lists? Experiment with lists vs. NumPy arrays in performance
# Measure time for list
# Measure time for NumPy array

# 1. NumPy’s code is written in C and C++, which is faster than Python’s interpreted code.
# 2. Numpy array perform operationsonentire array at once (vectorization)
# 3. it also store data in continuous memory block

import numpy as np
import time

py_list=[2,4,5,7,8]
t1=time.time()
for i in py_list:
    print(i+2)
t2=time.time()
print("Time taken by python list: ", t2 - t1)
print("-----------------------------------")

np_arr=np.array([2,4,5,7,8])
t3=time.time()
print(np_arr+2)
t4=time.time()
print("Time taken by numpy arrais: ",t4-t3)



4
6
7
9
10
Time taken by python list:  0.001001119613647461
-----------------------------------
[ 4  6  7  9 10]
Time taken by numpy arrais:  0.0


In [72]:
arr=np.array([2,4,6,8,7,9,0,3,5,6,7,8,2])
x= np.where(arr%2==0)
print(x)

(array([ 0,  1,  2,  3,  6,  9, 11, 12], dtype=int64),)


In [73]:
import numpy as np

In [74]:
arr=np.array([[8,3,4,6]])
arr[0,1] 

3

In [75]:
import numpy as np
arr=np.array([2,4,1,5,7,8])
new_arr=np.sort(arr)
print(new_arr)

[1 2 4 5 7 8]


In [76]:
arr=np.array(["red","Green","Red","blue","yellow","Maroon"])
print(np.sort(arr))
# print(type(arr))

['Green' 'Maroon' 'Red' 'blue' 'red' 'yellow']


In [77]:
arr=np.array([[2,3,4],[9,0,5],[7,3,7]])
print(np.sort(arr))

[[2 3 4]
 [0 5 9]
 [3 7 7]]


In [78]:
# boolen sorting
arr=np.array([True,True,False,True,True,False])
print(np.sort(arr))

[False False  True  True  True  True]


In [79]:
arr = np.array([[1, 3], [4, 1], [2, 5],[0,3]])
sorted_arr = arr[arr[:,1].argsort()]  # Sort by the second column
print("Sorted by second column (NumPy):\n", sorted_arr)

Sorted by second column (NumPy):
 [[4 1]
 [1 3]
 [0 3]
 [2 5]]


In [80]:

arr=np.array([2,5,3,7,4,8,9,6,8,3,2])
mask=arr>5
filtered_array=arr[mask]
print(np.sort(filtered_array))

[6 7 8 8 9]


In [81]:
# multiple condition for filter

arr=np.array([3,23,24,1,57,2,5,34,33,7,78])
mask=(arr > 10) & (arr % 2 == 0)
filtered_array = arr[mask]
print(np.sort(filtered_array))

[24 34 78]


In [82]:

arr = np.array([1,2,14,6,8,9])

filter_arr = []

for element in arr:
    if element>6:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

print(filter_arr)
print(np.sort(arr[filter_arr]))


[False, False, True, False, True, True]
[ 8  9 14]


In [83]:
arr = np.array(["Apple", "Cherry","Orange","Banana","Guavava", "Avocado", "Mango", "Apricot", "Berry"])

filter=np.char.startswith(arr,"A")
print(arr[filter])

filter=np.char.startswith(arr,"G")
print(arr[filter])

filter=np.char.endswith(arr,"do")
print(arr[filter])

filter=np.char.str_len(arr) > 6
print(arr[filter])

filter=np.char.find(arr,"ang")>0
print(arr[filter])


['Apple' 'Avocado' 'Apricot']
['Guavava']
['Avocado']
['Guavava' 'Avocado' 'Apricot']
['Orange' 'Mango']


In [84]:
arr=np.array([3,6,4,2,9,6])
filter=arr>4
print(arr[filter])

[6 9 6]


In [85]:
#this will return array of 10 values range from 0 to 1

arr=np.random.rand(1,2,3) # one layer 2 rows and 3 columns 
print(arr)

[[[0.03976662 0.64162274 0.7134313 ]
  [0.3261439  0.95135892 0.47102707]]]


In [86]:
# arr=np.array.random.randint(10) # one layer 2 rows and 3 columns 
# print(arr)

In [87]:
print(np.random.randint(20))
print(np.random.random_sample(10))

print("floating: ",np.random.uniform(10))

17
[0.181134   0.08093481 0.67723758 0.71603824 0.34169405 0.63970665
 0.28421856 0.91116712 0.75107788 0.1489056 ]
floating:  1.9639035746873148


In [88]:
from numpy import random
arr=random.randint(10,size=20) #this will create an array of size 20 in which numbers from 1 to 10 are included
# size keyword is used to define the size of an array / no of elements in an array

print(arr)
type(arr)

[3 1 3 2 2 1 1 7 8 7 8 5 7 9 6 8 8 8 3 2]


numpy.ndarray

In [89]:
arr=random.randint(10, size=(10))
print(arr)
print("---------------------")
arr=random.randint(10, size=(5,5))
print(arr)
print("---------------------")
arr=random.randint(10, size=(1,3,4))
print(arr)
print("---------------------")
arr=random.randint(10, size=(2,2,3,3))
print(arr)
print("---------------------")

[5 6 1 6 8 5 9 5 4 2]
---------------------
[[2 6 4 7 7]
 [7 9 0 0 3]
 [9 5 8 6 7]
 [2 8 4 8 1]
 [7 6 0 3 6]]
---------------------
[[[3 3 1 8]
  [1 3 7 3]
  [5 2 8 7]]]
---------------------
[[[[0 6 7]
   [4 5 4]
   [6 7 5]]

  [[2 7 4]
   [3 8 4]
   [2 6 2]]]


 [[[3 8 0]
   [5 5 2]
   [1 9 7]]

  [[8 1 0]
   [5 0 0]
   [0 7 3]]]]
---------------------


In [90]:
x=random.randint(100,size=10)
print(x)
print("--------------------------------")
y=random.choice(x)
print(y)

[30  6  4  2 21 48 34 99 94 50]
--------------------------------
99


In [91]:
arr = np.array(["Apple", "Cherry","Orange","Banana","Guavava", "Avocado", "Mango", "Apricot", "Berry"])
x=random.choice(arr)
print(x)


Avocado


In [109]:
from numpy import random 
arr=random.randint(10,size=10)

print(random.choice(arr))
print(arr)

8
[8 4 6 7 9 3 3 4 9 7]


In [104]:
import random
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
print(random.choices(numbers, k=3))  # Picks 3 random elements


[7, 7, 1]


In [18]:
# floating point random values

import numpy as np
from numpy import random

arr=np.random.uniform(1,10)  #print single floating point in between 1 to 10
print(arr)
print("-"*40)

arr=np.random.uniform(1,10,size=(3))  #generate 3 floating point numbers in between 1 to 10
print(arr)
print("-"*40)

arr=np.random.uniform(1,10,size=(3,4))  #generate floating point numbers in between 1 to 10 3 rows 4 columns
print(arr)
print("-"*30)

arr=np.random.uniform(1,10,size=(3,2,6))  # generate floating point numbers in between 1 to 10, 3 layer 2 rows 6 columns
print(arr)
print("-"*30)

1.279281193883781
----------------------------------------
[9.19820107 9.59557199 4.14206451]
----------------------------------------
[[5.2153425  2.71009956 8.70642086 6.47729862]
 [6.80740506 6.13072713 9.11284668 3.26579413]
 [4.94128481 3.22501211 1.33680101 9.24747069]]
------------------------------
[[[3.71859726 7.41970973 5.79933191 9.93566401 7.97860119 2.99231024]
  [9.7053845  6.73804368 7.48444206 2.07782124 8.3465218  9.37129335]]

 [[5.66800485 6.81853423 5.83539447 6.66071491 5.46675543 6.72630535]
  [4.50292879 8.75302445 1.52420776 9.86656922 7.51336682 7.81435657]]

 [[9.59604592 4.44688601 9.54099208 9.01554926 5.93001611 5.1391289 ]
  [5.39763783 8.96714036 4.39693503 3.10447816 5.23745262 3.43997501]]]
------------------------------


In [22]:
# normal distribution of numbers in an array of 5 elements
print(np.random.randn(5))
print("-"*80)

# normal distribution of numbers in 2D array having 3 rows 4 columns
print(np.random.randn(3,4))
print("-"*80)

[-1.8594979  -0.996699    0.23334011  0.16955575  0.61118298]
--------------------------------------------------------------------------------
[[ 0.88611989  0.17060373  0.55979693  0.16770378]
 [ 0.92721878  1.04921036 -1.42999625 -0.16818373]
 [-0.52856042 -0.08603903 -1.64939944  1.16519372]]
--------------------------------------------------------------------------------


In [110]:
arr=np.array([3,4,2,60,7,13,6,10,14])
print(np.random.choice(arr))
arr=np.array([3,4,2,60,7,13,6,10,14])
print(np.random.choice(arr, size=3))

3
[ 3  6 14]


In [111]:
arr=np.array(["Ahmed","Sanam","Kiran","Abid"])
print(np.random.choice(arr))


Kiran


In [112]:
arr=np.array(["Ahmed","Sanam","Kiran","Abid","Ali","Rabia"])
np.random.shuffle(arr)
print(arr) #Shuffle values/elements of original array

['Rabia' 'Kiran' 'Sanam' 'Abid' 'Ali' 'Ahmed']


In [113]:
x=np.random.choice([True,False], size=10)
print(x)

[False False  True False False  True False False  True  True]


In [77]:

np.random.seed(1)
print(np.random.randint(1, 10, size=10))


[6 9 6 1 1 2 8 7 3 5]


In [100]:
arr=np.random.randint(5, size=(5,5))
print(arr)
np.random.choice(10)

[[3 0 2 1 3]
 [2 0 1 4 1]
 [3 3 1 2 0]
 [2 4 0 2 4]
 [3 4 3 0 4]]


7

In [114]:
arr=random.randint(10, size=10)
user=int(input("Enter a number: "))

system=random.choice(10)
if user==system:
    print("You Won")   
else:
     print("You lose")

print("User Enter: ",user)
print("System Enter: ",system)


You lose
User Enter:  4
System Enter:  5


In [114]:
x=random.choice([0,1],size=(3,5))
print(x)

[[1 1 0 1 1]
 [1 1 0 1 0]
 [1 1 1 1 0]]


In [128]:
arr=np.array([3,6,2,9,8])
x=random.choice(arr, p=(0.2,0.4,0.2,0.1,0.1), size=(5,5))
print(x)

[[6 6 3 3 6]
 [6 2 6 6 9]
 [8 3 3 6 6]
 [3 2 6 3 2]
 [6 6 2 6 6]]


In [134]:
x = random.choice([3, 5, 7, 9], p=[0.1, 0.3, 0.4, 0.2], size=(100))

print(x)


count=0
count_3=0
count_5=0
count_7=0
count_9=0
for i in x:
    if ((i==5) |(i==3))|((i==7)|(i==9)):
        count+=1
    if i==3:
        count_3+=1
    if i==5:
        count_5+=1
    if i==7:
        count_7+=1
    if i==9:
        count_9+=1
        

print("Total Elements:",count)
print("Total Elements of 3:",count_3)
print("Total Elements of 5:",count_5)
print("Total Elements of 7:",count_7)
print("Total Elements of 9:",count_9)

total_count=count_3+count_5+count_7+count_9
print("Total Elements After:",total_count)

[5 3 7 5 7 5 5 7 7 7 7 9 5 7 5 9 5 3 5 3 5 7 7 5 7 5 5 9 7 5 5 9 7 3 3 7 5
 5 7 5 5 7 7 5 5 9 9 7 5 9 7 7 9 9 5 5 7 7 3 7 5 5 9 9 9 3 7 3 5 7 3 7 5 7
 7 7 5 9 5 3 5 5 7 5 5 9 9 5 7 5 3 5 7 3 7 7 5 7 7 7]
Total Elements: 100
Total Elements of 3: 12
Total Elements of 5: 37
Total Elements of 7: 36
Total Elements of 9: 15
Total Elements After: 100


In [ ]:
from numpy import random 
import numpy as np

In [115]:
# num=np.random.randint(1,25)
guess=0
while guess < 3:
    choice=int(input("Choose a number"))
    system=random.choice(3)
    if choice==system:
        print("You Won :)")
        print("Your choice: ",choice)
        print("System Choice choice: ",system)
        print("*"*30)
    else:
        print("Oh, You lose :(")

        print("Your choice: ",choice)
        print("System Choice choice: ",system)
        print("*"*30)
    guess+=1


Oh, You lose :(
Your choice:  3
System Choice choice:  2
******************************
Oh, You lose :(
Your choice:  2
System Choice choice:  0
******************************
Oh, You lose :(
Your choice:  5
System Choice choice:  2
******************************


In [43]:
# numpy mathematical operation
# universal operation
# these are the element wise univeersal operations 
# if we donot use universal functions we have to use loops to perform operation on each elements

arr1=np.array([10,2,42,25,18])
arr2=np.array([2,4,3,2,5])
arr3=[-2,-7,-8,-1]

print("Addition:    ",np.add(arr1,arr2))   #add corresponding elements of arr1 and arr2
print("Subtraction: ",np.subtract(arr1,arr2)) #subtract corresponding elements of arr1 and arr2
print("Multiplction:",np.multiply(arr1,arr2)) #Multipy corresponding elements of arr1 and arr2
print("Division:    ",np.divide(arr1,arr2)) #Divide corresponding elements of arr1 and arr2
print("Modulous:    ",np.mod(arr1,arr2)) #mod corresponding elements of arr1 and arr2
print("Power:       ",np.power(arr1,arr2)) #power corresponding elements of arr1 and arr2
print("Reminder:    ",np.remainder(arr1,arr2)) #Reminder corresponding elements of arr1 and arr2
print("Quot /Rem:   ",np.divmod(arr1,arr2)) #this will return 2 arrays first array of quotients and second for reminder of corresponding elements of arr1 and arr2
print("Absolute:    ",np.abs(arr3))
print("Square root: ",np.sqrt(arr2))
print("Exponent:    ",np.exp(arr2))
print("Truncate decimal:",np.trunc(np.exp(arr2))) #truncate will remove the decimal part only


# type(np.add)  this will return that add is a universal function

Addition:     [12  6 45 27 23]
Subtraction:  [ 8 -2 39 23 13]
Multiplction: [ 20   8 126  50  90]
Division:     [ 5.   0.5 14.  12.5  3.6]
Modulous:     [0 2 0 1 3]
Power:        [    100      16   74088     625 1889568]
Reminder:     [0 2 0 1 3]
Quot /Rem:    (array([ 5,  0, 14, 12,  3]), array([0, 2, 0, 1, 3]))
Absolute:     [2 7 8 1]
Square root:  [1.41421356 2.         1.73205081 1.41421356 2.23606798]
Exponent:     [  7.3890561   54.59815003  20.08553692   7.3890561  148.4131591 ]
Truncate decimal: [  7.  54.  20.   7. 148.]


In [51]:
arr=np.array([3.6775,5.87998,9.05471,2.1233])
print("Original  Array:                    ",arr)
print("Roundoff the whole Array:           ",np.around(arr))
print("Roundoff Array to 2 decimal numbers ",np.around(arr,2))
print("Roundoff Array to 3 decimal numbers ",np.around(arr,3))


Original  Array:                     [3.6775  5.87998 9.05471 2.1233 ]
Roundoff the whole Array:            [4. 6. 9. 2.]
Roundoff Array to 2 decimal numbers  [3.68 5.88 9.05 2.12]
Roundoff Array to 3 decimal numbers  [3.678 5.88  9.055 2.123]


In [61]:
# floor function--> this function will round down the number to its nearest value
arr = np.array([2.342,-3.45,0.897,-2.411])
print(np.floor(arr))

arr=np.array([3.234,3.25,8.365,5.896])
print(np.floor(arr))

[ 2. -4.  0. -3.]
[3. 3. 8. 5.]


In [62]:
# Ceil function--> this function will round up the number to its nearest value
arr = np.array([2.342,-3.45,0.897,-2.411])
print(np.ceil(arr))

arr=np.array([3.234,3.25,8.365,5.896])
print(np.ceil(arr))

[ 3. -3.  1. -2.]
[4. 4. 9. 6.]


In [93]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([3,5,7,2,1])
# np.add.reduce is used only with the scalar values means it only accept one argument
print("Add.reduce: ",np.add.reduce([arr1,arr2],axis=0)) #same as summation sum all elements wthin an array
print("Add.reduce: ",np.add.reduce([arr1,arr2],axis=1)) #same as summation sum all elements wthin an array
print("Add:",np.add(arr1,arr2)) # add corresponding elements of 2 arrays
print("Summation: ",np.sum([arr1,arr2], axis=0)) #add all the elements of both array 
print("Summation: ",np.sum([arr1,arr2], axis=1)) #add all the elements of individual array 

Add.reduce:  [ 4  7 10  6  6]
Add.reduce:  [15 18]
Add: [ 4  7 10  6  6]
Summation:  [ 4  7 10  6  6]
Summation:  [15 18]


In [97]:
# comulative Sum 

arr1=np.array([1,3,5,6,7,9])
arr2=np.array([2,3,5,6,3,1])
print("Comulative sum: ",(np.cumsum([arr1,arr2],axis=1)))
print("Sum: ",(np.sum([arr1,arr2],axis=1)))

Comulative sum:  [[ 1  4  9 15 22 31]
 [ 2  5 10 16 19 20]]
Sum:  [31 20]


In [98]:
# cumulative product
print("Comulative product: ",(np.cumprod([arr1,arr2],axis=1)))
print("Product: ",(np.prod([arr1,arr2],axis=1)))

Comulative product:  [[   1    3   15   90  630 5670]
 [   2    6   30  180  540  540]]
Product:  [5670  540]


In [105]:
x=36
y=25
print("lcm is ",np.lcm(x,y))

lcm is  900


In [109]:
arr=np.array([30,4,15,6,72])
print(np.lcm.reduce(arr))

360


In [129]:
arr=np.random.randint(1,10,size=10)
print(arr)
print(np.lcm.reduce(arr))



[1 1 1 2 2 3 3 2 3 8]
24


In [132]:
arr1 = np.array([12, 20, 15])
arr2 = np.array([18, 30, 25])

print(np.lcm(arr1,arr2))

[36 60 75]


In [142]:

arr1=np.array([15,12,30])
arr2=np.array([25,18,20])
print("Element wise: ",np.gcd(arr1,arr2))
print("Array wise: ",np.gcd.reduce(arr1))
print("Array wise: ",np.gcd.reduce(arr2))

Element wise:  [ 5  6 10]
Array wise:  3
Array wise:  1


In [148]:
print(np.pi/2)
print(np.sin(90))

1.5707963267948966
0.8939966636005579


In [149]:
arr=np.array([180,90,60,45,30])
print(np.radians(arr))

[3.14159265 1.57079633 1.04719755 0.78539816 0.52359878]


In [97]:
arr=np.array([3.14159265, 1.57079633, 1.04719755, 0.78539816, 0.52359878])
x=np.degrees(arr)
print(np.round(x))

[180.  90.  60.  45.  30.]


In [102]:
x=180
x=np.radians(x)
print(np.round(np.sin(x)))
print(np.round(np.cos(x)))
print(np.round(np.tan(x)))

0.0
-1.0
-0.0


In [115]:
x=90
x=np.radians(x)
print(np.isclose(np.sin(x),0))
print(np.isclose(np.cos(x),0))
print(np.isclose(np.tan(x),0))

False
True
False


In [117]:
x=45
x=np.radians(x)
print(np.sin(x),0)
print(np.cos(x),0)
print(np.tan(x),0)

0.7071067811865476 0
0.7071067811865476 0
0.9999999999999999 0


In [126]:
arr=np.array([np.pi, np.pi/2, np.pi/3, np.pi/4, np.pi/6])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))



[1.22464680e-16 1.00000000e+00 8.66025404e-01 7.07106781e-01
 5.00000000e-01]
[-1.00000000e+00  6.12323400e-17  5.00000000e-01  7.07106781e-01
  8.66025404e-01]
[-1.22464680e-16  1.63312394e+16  1.73205081e+00  1.00000000e+00
  5.77350269e-01]


In [125]:
arr=np.array([0, 0.5, 1, -0.5, -1])
print("Inverse--------------------------")
print(np.degrees(np.arcsin(arr)))
print(np.degrees(np.arccos(arr)))
print(np.degrees(np.arctan(arr)))

Inverse--------------------------
[  0.  30.  90. -30. -90.]
[ 90.  60.   0. 120. 180.]
[  0.          26.56505118  45.         -26.56505118 -45.        ]


In [127]:
base=4
perp=8
print(np.hypot(base,perp))

8.94427190999916
